### ISSUE TITLE
does not compile with ES 2.0.0

### ISSUE THREAD

**Issue by ivukotic** [sscarduzio/elasticsearch-readonlyrest-plugin#11]

**Comment by sscarduzio** [comment]
Thanks for reporting @ivukotic I'll have a look asap.

**Comment by sscarduzio** [comment]
@ivukotic here you go buddy. 
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.4_es-v2.0.0.zip?raw=true

**Comment by ivukotic** [comment]
Hi,

that was really quick! Thanks a lot.

while you are at it… I noticed that the plugin blocks Marvel (and Marvel is for free in ES2).
I happens due to Marvel issuing POSTs  directly from a users browser. Would you think there is a way to recognize it?

Thanks,
Ilija

On Nov 10, 2015, at 9:08 , Simone Scarduzio <notifications@github.com<mailto:notifications@github.com>> wrote:


@ivukotic<https://github.com/ivukotic> here you go buddy.
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.4_es-v2.0.0.zip?raw=true

**Comment by sscarduzio** [comment]
@ivukotic you could tune the ACLs to allow POST, together with a url_re that matches the marvel plugin.

```
readonlyrest:
    enable: true
    response_if_req_forbidden: Sorry, your request is forbidden

    access_control_rules:
    - name: full access to internal servers
      type: allow
      hosts: [127.0.0.1, 10.0.0.20, 10.0.2.112]

    - name: forbid access to private index from external hosts
      type: forbid
      uri_re: ^http://localhost:9200/reservedIdx/.*
 
    ### ADD THIS RULE FOR MARVEL
    - name: allow POST if we're hitting Marvel plugin 
      type: allow
      method: [POST]
      uri_re: ^http://.*/_plugin/marvel.*

    - name: restricted access to all other hosts
      type: allow
      methods: [OPTIONS,GET]
      maxBodyLength: 0
```

NB: this is not tested, but you got the gist :)
Tell me how it goes, and don't forget to star the project if you like it!
