### ISSUE TITLE
Support of Kibi 

### ISSUE THREAD

**Issue by nitram4** [sscarduzio/elasticsearch-readonlyrest-plugin#119]
Im investigating support for Kibi (for of Kibana used for relational analysis). 
I have successfully started Kibi (has own plugin for ES) together with readonlyplugin. 
Kibi saves its data to .kibi index, so I wanted to reuse the capability of controlling Kibi the same way as Kibana. 

My configuation is like this: 

```
name: Full Admin (now for Kibi) - access outside Kibana
type: allow
kibana_access: rw
kibana_index: .kibi
auth_key: kibiadmin:XXXXXXXX
```

Error message is: 

```
[2016-10-24 18:25:01,460][DEBUG][plugin.readonlyrest.acl.blocks.rules.impl] Login as: kibiadmin rc: { action: indices:data/read/coordinate-search, OA:10.xx.xx.xx, indices:[.kibi], M:POST, P:/.kibi/dashboard/_coordinate_search, C:{"query":{"match_all":{}}}

[2016-10-24 18:25:01,460][DEBUG][plugin.readonlyrest.acl.blocks.rules.impl] KIBANA ACCESS DENIED { action: indices:data/read/coordinate-search, OA:10.xx.xxx.xx, indices:[.kibi], M:POST, P:/.kibi/dashboardgroup/_coordinate_search, C:{"query":{"match_all":{}}}
```

What is strange for me is, that I see there is another option indices:data/read/coordinate-search which is new to Kibi and its not working even when Im not limiting Action. 
When the rules are simple like this

```
  - name: Full Admin (now for Kibi) - access outside Kibana
      type: allow
      auth_key: kibiadmin:XXXXX

```

it works. Any clues? Thanks

**Comment by sscarduzio** [comment]
well, `kibana_access:rw` is not letting everything pass. It allows just the minimum set of actions to the minimum set of indices to make Kibana read indices and save its own object to `.kibana` index.

It's rather expected that another product requests a slightly differently set of actions. If Kibi gets blocked only on a small amount of extra actions, you might want to white list those in an **additional** rule block:

```yml
name: Full Admin (now for Kibi) - access outside Kibana
type: allow
kibana_access: rw
kibana_index: .kibi
auth_key: kibiadmin:XXXXXXXX

name: Full Admin (now for Kibi) - access outside Kibana (EXTENDED)
type: allow
actions: ["indices:data/read/coordinate-search"]
indices: [".kibi"]
auth_key: kibiadmin:XXXXXXXX
```
