### ISSUE TITLE
ES 2.0 + Marvel Compatibility

### ISSUE THREAD

**Issue by sscarduzio** [sscarduzio/elasticsearch-readonlyrest-plugin#12]
Carrying over from a discussion in #11 with @ivukotic 

>Hi,

>What marvel is trying to do is this:

>curl -XPOST http://cl-analytics.mwt2.org:9200/.marvel-2015.11.10/_search -d '{"facets":{"query":{"terms":{"field":"node.name","size":100},"facet_filter":{"fquery":{"query":{"filtered":{"query":{"query_string":{"query":"_type:node_stats"}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"from":1447119335396,"to":1447122935396}}}]}}}}}}}},"size":0}’

>so I made what you suggested:
>uri_re: ^http://.*.marvel.*_search.*

>but the access is still not possible. Does it have to be on all the machines or only on the master node?

>Thanks,
>Ilija

**Comment by sscarduzio** [comment]
Hey @ivukotic, better late than ever:  it was the wrong regex, sorry. The conf that works is this:
```
 readonlyrest:
    enable: true
    response_if_req_forbidden: <h1>Forbidden</h1>
    access_control_rules:
    - name: ALLOW MARVEL
      type: allow
      methods: [POST]
      uri_re: ^?\.marvel.*_search
    - name: readonly
      type: allow
      methods: [OPTIONS,GET]
      maxBodyLength: 0

```
