### ISSUE TITLE
groups: empty user list should not disable groups rule entirely

### ISSUE THREAD

**Issue by maitai** [sscarduzio/elasticsearch-readonlyrest-plugin#121]
Consider the following scenario:

```
readonlyrest:
  enable: true
  access_control_rules:

  - name: myblock
    type: allow
    indices: ["myindex"]
    groups: ["mygroup"]

  users:
  - username: alice
    auth_key: alice:p455wd
    groups: ["mygroup"] 
```
Only Alice has access to `myindex`. All fine there.

Now let's _empty out_ her user groups to make the index completely private for a moment:
```
  users:
  - username: alice
    auth_key: alice:p455wd
    groups: []              # <-- removed "mygroup" from the list to revoke access
```
**Expected outcome**:
Alice loses access to `myindex`.
**Actual outcome**:
The index can be accessed by Alice _**and the rest of the world**_.

**Reason**: Alice is not added to the internal user list because of her `groups` list beeing empty. With no other users configured, this leads to a completely empty user list as well. No harm until here, but this on the other hand leads to a _RuleNotConfiguredException_ for the `groups` rule ([source](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/dedd1c45c4d593f1e903b11550bf13093a6d0061/src/main/java/org/elasticsearch/plugin/readonlyrest/acl/blocks/rules/impl/GroupsRule.java#L40-L42)) inside the `myblock` ACL block. So as soon as Alice's  groups are empty (or more generally: if all groups of all users are empty), the groups rule disappears from the block leaving the corresponding index unprotected.

**Proposition**: The _RuleNotConfiguredException_ should not be thrown on an empty user list.
