### ISSUE TITLE
Spammy logging, v1.12.1_es-v2.4.1

### ISSUE THREAD

**Issue by teebu** [sscarduzio/elasticsearch-readonlyrest-plugin#130]
I just installed latest version, and my ES log is showing all the activity, unlike the previous version, which only showed denied access. 

How do I fix this? I tried editing the logging.yml with these, didn't remedy the spam:

```  
  plugin.readonlyrest.acl.blocks.rules.impl: INFO
  plugin.readonlyrest.acl: INFO
```

I'd still like to see what was denied, pretty much I liked what was shown by default in the previous version.

Adding 

```
additivity:
 #Plugin readonly rest exclusion from ES main log file
  plugin.readonlyrest.acl.blocks.rules.impl: false
  plugin.readonlyrest.acl: false
```

Threw an error:

```
log4j:WARN No appenders could be found for logger (plugin.readonlyrest.acl).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

### So far, solution:

```  
  plugin.readonlyrest.acl.blocks.rules.impl: INFO
  plugin.readonlyrest.acl: OFF
```
