### ISSUE TITLE
[Question] IP filtering

### ISSUE THREAD

**Issue by zidane28** [sscarduzio/elasticsearch-readonlyrest-plugin#149]
Just want to ask, can this plugin do IP filtering? Means just allow certain IP to access elasticsearch.

If possible, can anyone help to detail out?

Because I still can't find a way to do it after I read on the Wiki...

**Comment by sscarduzio** [comment]
@zidane28 sure, sorry for the messy docs, I'm actually about to work on improving this extensively in the official site, rather than random pages in GH.

To your question, try something like this:

```yml
readonlyrest:
    enable: true
    access_control_rules:
    - name: "Accept any requests coming from this ip, nothing else"
      type: allow
      hosts: [9.9.9.9]
```

Keep in mind that in this plugin, the default policy is to forbid all the requests. So the above single rule will allow requests coming exclusively from the IP address 9.9.9.9.

I hope this helps,

_S
