### ISSUE TITLE
Visualization showing data only from ona day index

### ISSUE THREAD

**Issue by gulycka** [sscarduzio/elasticsearch-readonlyrest-plugin#154]
Hello guys,

recently I observed the problem with readonlyrest plugin. I created visualization and set the time frame to 7 days (or anything else). Any type of visualization showed me data only from one day. Via discover tab I am able to display all the data, not only the data from one day. Problem happens only with visualizations. I am using the admin user that has full access rights. See the elasticsearch configuration:

```
readonlyrest:
    enable: true
    response_if_req_forbidden: Sorry, your request is forbidden.
    access_control_rules:

    - name: ADMIN
      auth_key_sha1: *******
      type: allow
```

The problem also occurs with other indices.

See the Bar chart visualization with Data histogram below:

![1](https://cloud.githubusercontent.com/assets/3018848/22099375/6687b222-de2b-11e6-9ee4-6588e5e4d02b.png)

Check the discovery tab with the same time frame, the data from other days is there:

![2](https://cloud.githubusercontent.com/assets/3018848/22099381/690d3936-de2b-11e6-8ba8-ab24a095f20c.png)

I tried to turn off the readonlyrest plugin by configuration change:
```
$ cat /etc/elasticsearch/elasticsearch.yml
readonlyrest:
    enable: false
    response_if_req_forbidden: Sorry, your request is forbidden.
    access_control_rules:

$ service elasticsearch force-reload
```

Then I refreshed the same visualization and everything works just fine:

![3](https://cloud.githubusercontent.com/assets/3018848/22099383/6ffa0008-de2b-11e6-99f4-09835e1f6282.png)

Versions of ELK and plugin:
Elasticsearch 2.4.3
Readonlyrest plugin 1.13.0
Kibana 4.5.4

Thanks.
