### ISSUE TITLE
Cannot enable http.type: ssl_netty4 on 5.1.2

### ISSUE THREAD

**Issue by dwjvaughan** [sscarduzio/elasticsearch-readonlyrest-plugin#161]
When trying to enable SSL with the below:

```
http.type: ssl_netty4
readonlyrest:
    enable: true
    ssl:
      enable: true
      keystore_file: "/etc/elasticsearch/keystore/readonlyrest.jks"
      keystore_pass: readonlyrest
      key_pass: readonlyrest

    response_if_req_forbidden: Sorry, your request is forbidden.

    access_control_rules: ...
```
In the logs I'm seeing:

[2017-02-01T15:54:03,260][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.IllegalArgumentException: http type setting [http.type] must be one of [security3,security4]
