### ISSUE TITLE
Medium issue : es 2.4.1 kibana 4.6.3 ROR 1.13.2 | Groups access

### ISSUE THREAD

**Issue by ld57** [sscarduzio/elasticsearch-readonlyrest-plugin#165]
Hi again,

@sscarduzio @Shifter2600 , I was implementing group access when I meet again the issue regarding our method of partial pattern in kibana (log*  or public-*), and results : 

here my full config group : 

```
 readonlyrest:
    enable: true
    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin
    access_control_rules:

    - name: ELKG admin
      type: allow
      actions: ["cluster:*", "indices:*", "org.xbib.elasticsearch.knapsack.*"]
      groups: ["superadmin"] 
#OK   service kibana   
    - name: Kibana Server (we trust this server side component, full access granted via HTTP authentication)
      auth_key_sha1: f435b3e2343425345345abfbc5e96273028f
      type: allow
      hosts: [127.0.0.1]
#OK   to prevent data
    - name: non admin (prevent data)
      type: forbid
      uri_re: (_node|_cluster|_cat|_task|_plugin)
      
#OK   to autorise data
    - name: superadmin (autorise data)
      type: allow
      uri_re: (_node|_cluster|_cat|_task|_plugin)
      groups: ["superadmin"]

#OK   dummy account
    - name: Dummy (to permit request for basic authentication popup)
      auth_key: dummy:dummy
      type: forbid

#OK   security
    - name: Security team
      type: allow
      kibana_access: ro
      indices: ["<no-index>", ".kibana*","home", "log_lu_ei_sys_sec_paloalto*"]
      groups: ["security"]

#OK    exchange
    - name: exchange team
      type: allow
      kibana_access: ro
      indices: ["<no-index>", ".kibana*","home", "log_lu_ei_sys_exchange*"]
      groups: ["exchange"]

#OK    dnsint
    - name: dns team
      type: allow
      kibana_access: ro
      indices: ["<no-index>", ".kibana*","home", "log_lu_ei_sys_dnsint*"]
      groups: ["dnsint"]

#OK   admin
    - name: admin team
      type: allow
      kibana_access: ro
      indices: ["<no-index>", ".kibana*","home", "log_lu_ei_sys_metricbeat*", "watcher", "watcher_alarms"]
      groups: ["admin"]

#OK   esx
    - name: esx team
      type: allow
      kibana_access: ro
      indices: ["<no-index>", ".kibana*","home", "log_lu_ei_sys_esx*"]
      groups: ["esx"]

#OK    winevent
    - name: winevent team
      type: allow
      kibana_access: ro
      indices: ["<no-index>", ".kibana*","home", "log_lu_ei_sys_winevent*"]
      groups: ["winevent"]

#OK    printing
    - name: printing team
      type: allow
      kibana_access: ro
      indices: ["<no-index>", ".kibana*","home", "log_lu_ei_sys_printing*"]
      groups: ["printing"]

    users:
    - username: Adm_elkg
      auth_key_sha1: 9907e2746456546456c351f1b20bd
      groups: ["superadmin"]
  
    - username: test1
      auth_key_sha1: ab1d54a70745645645642f0057efbec
      groups: ["printing","exchange"]

    - username: test2
      auth_key_sha1: 435487905479583479853479543
      groups: ["exchange", "printing"]

```
in kibana, I defined a pattern "log*"  ( to consolidate all sources )
When login with Adm_elkg (full access), I can read data from kibana discover tab , from log* pattern, and i see data from all Es indices.

When login with user test1, I should normally see only data from ES indices "printing and exchange". but I see only the "printing" one.

When login with user test2, I should normally see only data from ES indices "printing and exchange". but I see only the "printing" one.

on another hand, reading kibana pattern log_lu_ei_sys_printing* or log_lu_ei_sys_exchange* works fine.

when testing previously without group, I have in mind that it was working. I will test this now (define access directly to user), and report back.
If it works, then there still is an issue regarding just the population of authorized indices, related to groups implementation.

Ld

**Comment by ld57** [comment]
I confirm , the config below works fine
```
 readonlyrest:
    enable: true
    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin
    access_control_rules:

    - name: Kibana Server (we trust this server side component, full access granted via HTTP authentication)
      auth_key_sha1: f435b3e697e3565465464c5e96273028f
      type: allow
      hosts: [127.0.0.1]

    - name: test1
      # auth_key is good for testing, but replace it with `auth_key_sha1`!
      auth_key: test1:test1
      type: allow
      kibana_access: ro
      indices: ["<no-index>", ".kibana*", "log_lu_ei_sys_exchange*", "log_lu_ei_sys_dnsint*", "log_lu_ei_sys_printing*", "home"]

    - name: test2
      # auth_key is good for testing, but replace it with `auth_key_sha1`!
      auth_key: test2:test2
      type: allow
      kibana_access: ro
      indices: ["<no-index>", ".kibana*", "log_lu_ei_sys_exchange*", "log_lu_ei_sys_printing*", "home"]
      
    - name: Dummy (to permit request for basic authentication popup)
      auth_key: dummy:dummy
      type: forbid
          
```

going to reduce the groups stuff on top, and just isolate test1 and test2 , also block group definition for dnsint, exchagne and printing, and let s retry

**Comment by ld57** [comment]
ok I redo the test for group with : 

```
 readonlyrest:
    enable: true
    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin
    access_control_rules:

#OK   service kibana   
    - name: Kibana Server (we trust this server side component, full access granted via HTTP authentication)
      auth_key_sha1: f435b3e697e3ddea23189436abfbc5e96273028f
      type: allow
      hosts: [127.0.0.1]

#OK   dummy account
    - name: Dummy (to permit request for basic authentication popup)
      auth_key: dummy:dummy
      type: forbid
#OK    exchange
    - name: exchange team
      type: allow
      kibana_access: ro
      indices: ["<no-index>", ".kibana*","home", "log_lu_ei_sys_exchange*"]
      groups: ["exchange"]
#OK    dnsint
    - name: dns team
      type: allow
      kibana_access: ro
      indices: ["<no-index>", ".kibana*","home", "log_lu_ei_sys_dnsint*"]
      groups: ["dnsint"]
#OK    printing
    - name: printing team
      type: allow
      kibana_access: ro
      indices: ["<no-index>", ".kibana*","home", "log_lu_ei_sys_printing*"]
      groups: ["printing"]

    users:
    - username: test1
      auth_key: test1:test1
      groups: ["exchange", "printing", "dnsint"]
  
    - username: test2
      auth_key: test2:test2
      groups: ["exchange","printing"]

```

well, 
user test1 can see in kibana discover , with pattern "log*" only data from exchange, but not dnsint and printing.
user test2 can see in kibana discover , with pattern "log*" only data from exchange, but not printing.

I would say it is related to groups, it should build authorized indices array by adding block by block.

or did I do something wrong ?

Ld
