### ISSUE TITLE
How to configure authentication in Kibana?

### ISSUE THREAD

**Issue by avtomonstr** [sscarduzio/elasticsearch-readonlyrest-plugin#171]
Hi!

1st of all I wan't to thank you for such a great plugin!

But I was doing my best to configure authentication in Kibana using readonlyrest plugin and still it doesn't work.
Can't you please create some small guide or give me a link if it is already created?

**Comment by danielmotaleite** [comment]
In kibana.yml, add something like this:

```
elasticsearch.url: "http://elasticsearch.domain:9200"
elasticsearch.username: "kibana"
elasticsearch.password: "password"

```

this will allow kibana internally to access elasticssearch. Users later trying to access kibana will be required also to authenticate with elasticsearch

**Comment by sscarduzio** [comment]
And in elasticsearch.yml you put this, as seen in our README.md file:
```yml
readonlyrest:
    enable: true
    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin

    access_control_rules:
    - name: "::KIBANA-SRV::"
      # auth_key is good for testing, but replace it with `auth_key_sha1`!
      auth_key: kibana:password
      type: allow
```

Now the Kibana process and Elasticsearch communicate using credentials.
Once you verify that Kibana connects to elasticsearch with no errors and reaches the green state (read Kibana logs), let's add a user for the browser to login.

```yml
    - name: "::RW DEVELOPER::"
      auth_key: rw:passwd
      type: allow
      kibana_access: rw
```

Now you should open Kibana in your browser and you'll be prompted for username and password, you put: username=rw and password=passwd.

NB:once you got this working , in order for these exchange of credentials to be secure, you **need** to enable SSL. Refer to the [encryption chapter in the official documentation](https://readonlyrest.com/documentation#toc-1-1-encryption).
