### ISSUE TITLE
Basic Auth feature not adhering to specs

### ISSUE THREAD

**Issue by sscarduzio** [sscarduzio/elasticsearch-readonlyrest-plugin#18]
The original pull request (https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/pull/9/files#diff-1903ac875e0e210c93a416feb366b81bR91) does not conform to HTTP basic auth. 

Ref: https://en.wikipedia.org/wiki/Basic_access_authentication

**Comment by sscarduzio** [comment]
Please re-download the 2.1.1 plugin as for #17. It should now work like this

```yml
...
    - name: Allow Basic auth
      type: allow
      auth_key: secret
```
And test it like this:
```
curl -H "Authorization:Basic c2VjcmV0" localhost:9200
```

Where c2VjcmV0 is the Base64 for "secret

**Comment by avadhootha** [comment]
Thanks for your quick resolution. It's working good and as expected.

**Comment by avadhootha** [comment]
Also a question.. Is there a way to have Api/Auth key rule and GET allow method rule at a time ?
I want to give **read access** to the users only with API or Basic Auth key. I can always the Get method restriction at the nginx and api rule in elasticsearch yml, but I need to know if there is any way we could do this through this plugin.
Thanks

**Comment by sscarduzio** [comment]
Sure you can, and it's super easy! Keep in mind:
* by default the plugin will block any request
* rule attributes work in AND to each other
* rules are in AND to each other

To your requirements:
```yml
  - name: Allow Readonly access, only if basic auth is satisfied.
      type: allow
      auth_key: secret
      methods: [OPTIONS,GET] # browsers might need the option, feel free to omit
      maxBodyLength: 0 # makes sure people don't put any write request in GET bodies (for readonly)
```

If no other rule is present, any other request (coming through the REST API) will be dropped.
