### ISSUE TITLE
Sending logs with Beats using SSL -> Rest

### ISSUE THREAD

**Issue by fnzv** [sscarduzio/elasticsearch-readonlyrest-plugin#198]
Hello,
I'm trying to ship some logs directly from Beats to an Elasticsearch Cluster with Rest plugin.
I have used the basic configuration with SSL enabled:
```yml
http.type: ssl_netty4
readonlyrest:
    enable: true
    ssl:
      enable: true
      keystore_file: "/elasticsearch/plugins/readonlyrest/keystore.jks"
      keystore_pass: readonlyrest
      key_pass: readonlyrest

    response_if_req_forbidden: Forbidden

    access_control_rules:
..
..
```
(Copy Pasted from your Doc the ACL rules)

But from the shipper logs i see:
2017-04-01T16:49:08Z ERR Connecting error publishing events (retrying): Get https://myserverip:9200: read tcp mylocalip:59926-> myserverip:9200: read: connection reset by peer

Do i need to set some flag to allow unverified SSL connections to ES or there is no support for direct SSL connections to Rest via Beats?

I want to use direct SSL connections to ES to avoid using a Logstash in the middle
