### ISSUE TITLE
Is proxy_auth compatible with ldap_auth?

### ISSUE THREAD

**Issue by ishergin** [sscarduzio/elasticsearch-readonlyrest-plugin#203]
I need to check if a user from http header x-forwarded-user belongs ldap group

So doesn't work:

```
  access_control_rules:
    ...
    - name: "test"
      type: allow
      ldap_auth:
        - name: 'main'
          groups: ['test']
      proxy_auth: '*'
      indices: ['test', '.kibana']

  ldaps:

  - name: main
    host: <>
    ...
```
