### ISSUE TITLE
I couldn't setup indices wise authorization based on the group

### ISSUE THREAD

**Issue by Rajeshkumar123** [sscarduzio/elasticsearch-readonlyrest-plugin#219]
Hi Team,

I have two indices where I need to authorize it based on the user and group.
This is the my **elasticsearch.yml** setup 

```
readonlyrest:
    enable: true
    response_if_req_forbidden: Sorry, your request is forbidden.
    
    ssl:
      enable: true
      keystore_file: "/root/lk/software/readonlyrest_ssl/keystore.jks"
      keystore_pass: readonlyrest
      key_pass: readonlyrest

    access_control_rules:

    - name: "Block 1 - Allowing anything from localhost"
      type: allow
      hosts: [127.0.0.1, xx.xx.xx.xxx, xx.xx.xx.xxx]
      
    - name: Accept requests from users in group xxx on xxxIndex
      type: forbid
      groups: ["application"]
      indices: ["logstash-ff.app_log"]

    - name: Accept requests from users in group team2 on index2
      type: forbid
      groups: ["customer"]
      indices: ["logstash-ff.customer_log"]
      
    - name: Kibana Read Only User (Kibana Read Only User)
      auth_key: app:xxxxxx
      type: forbid
      kibana_access: ro
      indices: ["logstash-ff.customer_log"]
    
      
    users:

    - username: app
      auth_key: app:xxxxxxx
      groups: ["application"]

    - username: customer
      auth_key: customer:xxxxxx
      groups: ["customer"]
```

**My Kibana setup(kibana.yml)**

```
elasticsearch.username: "app"
elasticsearch.password: "********"
```

When  try to hit my kibana url its not prompting for username and password also.. I tried to login as different user(app and customer) . I can view and edit all the indices. 

Let me know what I am missing in the configuration setup.

Thanks,
Rajeshkumar

**Comment by sscarduzio** [comment]
First of all, is your Kibana running in localhost?

**Comment by Rajeshkumar123** [comment]
My kibana is running in specific ip not in localhost.

```
# Using "Basic HTTP Auth" from browsers, can RW Kibana settings, RO on logstash indices from 2017 .
    - name: "::RW DEVELOPER::"
      auth_key: rw:dev
      type: allow
      kibana_access: rw
      indices: [".kibana", ".kibana-devnull", "logstash-2017*"]

    # Same as above, but cannot change dashboards, visualizations or settings in Kibana
    - name: "::RO DEVELOPER::"
      auth_key: ro:dev
      type: allow
      kibana_access: ro
      indices: [".kibana", ".kibana-devnull", "logstash-2017*"]
```

For this do I need to add the username and password in kibana. Do I need to install any additional plugin for this in kibana. I am using kibana 5.2.1 and elasticsearch 5.2.1

**Comment by Rajeshkumar123** [comment]
When I changed my elasticsearch.yml setup as below. I couldn't access any index in elasticsearch it throwing authorization exception for all index.

 Here is my modified code.

```
readonlyrest:
    enable: true
    response_if_req_forbidden: Sorry, your request is forbidden.
    
    #ssl:
    #  enable: true
    #  keystore_file: "/root/elk/elk_software/readonlyrest_ssl/keystore.jks"
    #  keystore_pass: readonlyrest
    #  key_pass: readonlyrest

    access_control_rules:
      
    - name: Kibana Read Only User (Kibana Read Only User)
      auth_key: app:toyota123
      type: allow
      kibana_access: ro
      indices: ["logstash-ff.customer_log"]
```

**Comment by sscarduzio** [comment]
You're missing the ::KIBANA-SRV:: block. And you're missing also to configure Kibana username and password (as the docs explicitly say).

**Comment by Rajeshkumar123** [comment]
I have included the `::KIBANA-SRV:: block` and I configured the kibana.yml. Still I am getting the authorization exception when I try to hot Kibana. Is it possible for you to provide a clear sample or document to configure it as per my requirement. It would be a great help.

```
[readonlyrest:
    enable: true
    response_if_req_forbidden: Sorry, your request is forbidden.
    
    #ssl:
    #  enable: true
    #  keystore_file: "/root/lk/lk_software/readonlyrest_ssl/keystore.jks"
    #  keystore_pass: readonlyrest
    #  key_pass: readonlyrest

    access_control_rules:
      
    - name: "::KIBANA-SRV::"
      # auth_key is good for testing, but replace it with `auth_key_sha256`!
      auth_key_sha256: root:xxxxxxx
      verbosity: error # don't log successful request
      type: allow
      
    - name: Kibana Read Only User (Kibana Read Only User)
      auth_key: root:xxxxxxx
      type: allow
      kibana_access: ro
      indices: [".kibana",".kibana-devnull","logstash-ff.customer_log"]]
```

```
**My Kibana.yml**

elasticsearch.username: "root"
elasticsearch.password: "toyota123"
```

**Comment by Rajeshkumar123** [comment]
@sscarduzio Atleast I would like to know what I am trying is possible in this plugin or not?..

**Comment by sscarduzio** [comment]
your requirement is quite confusing, there is no "customer" user in your configuration. How do you expect it to work?

**Comment by Rajeshkumar123** [comment]
@sscarduzio . I have updated my comment above. Do I need to add the "app" and "customer " username and password in `kibana.yml` also

**Comment by sscarduzio** [comment]
### Questions
1. You wrapped all the yaml in some square brackets. Why?

2. According to the yaml,  the `app` user can see `logstash-ff.customer_log`. Conversely, `customer` user can see `logstash-ff.app_log`. This is exactly the opposite you described.

**Comment by Rajeshkumar123** [comment]
@sscarduzio 
1. Square bracket is type error.
2. `app `user wants to see only `logstash-ff.app_log` and customer should only see `logstash-ff.customer_log`. I am not sure how to setup this one.

**Question**

1. Do I need to add the app and customer credentials which I used in `auth_key` in `kibana.yml`

**Comment by sscarduzio** [comment]
kibana.yml only needs credentials from the KIBANA-SRV block. Kibana users will provide their credentials to the browser. This should work.

**Comment by sscarduzio** [comment]
kibana users will share the same viz and dashboards, but will see different logs (provided that kibana is configured to look into "logstash-*"

**Comment by Rajeshkumar123** [comment]
> If kibana.yml only needs credentials from the KIBANA-SRV block

Then how kibana will identify which user was logged in and which index should be hide to them. How it will throw the access denied exception when the user `app` tries to access the index `logstash-ff.customer_log`. 

Sorry for two many questions . I am little bit confused with this configuration and I couldn't get clear pic from the documentation. I am just looking to understand utlise your plugin.

**Comment by sscarduzio** [comment]
kibana knows nothing about what user is logged in, ES knows. Kibana transparently proxies the majority of the http requests to ES, where this plugin lives.

**Comment by Rajeshkumar123** [comment]
> access_control_rules:
>       
>     - name: "::KIBANA-SRV::"
>       # auth_key is good for testing, but replace it with `auth_key_sha256`!
>       auth_key_sha256: root:xxxxxxx
>       verbosity: error # don't log successful request
>       type: allow
>       
>     - name: Kibana Read Only User (Kibana Read Only User)
>       auth_key: app:xxxxxxx
>       type: allow
>       kibana_access: ro
>       indices: [".kibana",".kibana-devnull","logstash-ff.customer_log"]]
> 
>     - name: Kibana Read Only User (Kibana Read Only User)
>        auth_key: customer:xxxxxxx
>        type: allow
>         kibana_access: ro
>         indices: [".kibana",".kibana-devnull","logstash-ff.app_log"]



In this setup what happens when a user app tries to access the `logstash-ff.customer_log` using `curl -XGET "http://localhost:9200/logstash-ff.customer_lo"`

**Comment by Rajeshkumar123** [comment]
I logged into as user `app` and I am getting the following error message when I try to access any index including `logstash-ff.app_log` 
**Error message**: `Sorry, your request is forbidden.`

**Comment by sscarduzio** [comment]
Ok I tried with ES and Kibana 5.4.0
- I loaded logstash indices from 2016 and 2017
- Set up two readonly users: simone and simone1. 
- Authorized the two users to 2016 and 2017 logs respectively
- launched Kibana
- Verified that logging in as either, I could see the respective set of logs.

Below my ES configuration:

```yml
readonlyrest:
    enable: true
    access_control_rules:

    - name: kibana
      type: allow
      auth_key: kibana:kibana
      verbosity: error

    - name: "::LOGSTASH::"
      type: allow
      auth_key: logstash:logstash
      actions: ["indices:admin/types/exists","indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create"]
      indices: ["logstash-*", "simone_logstash*", "logstash*"]
      #indices_rewrite: ["^logstash-.*", "simone_$0"]

    - name: "::RO::"
      type: allow
      auth_key: simone:ro
      kibana_access: ro
      indices: [".kibana", ".kibana-devnull", "logstash-2016*"]

    - name: "::RO::"
      type: allow
      auth_key: simone1:ro
      kibana_access: ro
      indices: [".kibana", ".kibana-devnull", "logstash-2017*"]

    - name: "::RW::"
      type: allow
      auth_key: simone:rw
      kibana_access: rw
```

Here is kibana.yml

```yml
elasticsearch.username: "kibana"
elasticsearch.password: "kibana"
```
All works for me, so please copy this example, see it working too and start making your changes AFTER you see this test case working.

**Comment by Rajeshkumar123** [comment]
I am using ES and Kibana 5.2.1

Find my below updated code as per your suggestion

```
readonlyrest:
    enable: true
    access_control_rules:

    - name: kibana
      type: allow
      auth_key: kibana:kibana
      verbosity: error

    - name: "::LOGSTASH::"
      type: allow
      auth_key: logstash:logstash
      actions: ["indices:admin/types/exists","indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create"]
      indices: ["logstash-*", "logstash*"]

    - name: "::RO::"
      type: allow
      auth_key: app:app123
      kibana_access: ro
      indices: [".kibana", ".kibana-devnull", "logstash-ff.app_log"]

    - name: "::RO::"
      type: allow
      auth_key: customer:app123
      kibana_access: ro
      indices: [".kibana", ".kibana-devnull", "logstash-ff.customer_log"]
```

Here is kibana.yml

```
elasticsearch.username: "kibana"
elasticsearch.password: "kibana"
```

I logged into the app server and I tried to access the indices.

```
curl -XGET localhost:9200/logstash-ff.customer_log
Forbidden
curl -XGET localhost:9200/logstash-ff.app_log
Forbidden
```

Same for Customer user.. 

```
curl -XGET localhost:9200/logstash-ff.customer_log
Forbidden
curl -XGET localhost:9200/logstash-ff.app_log
Forbidden
```
