### ISSUE TITLE
LDAP Error

### ISSUE THREAD

**Issue by shubhamverma27** [sscarduzio/elasticsearch-readonlyrest-plugin#240]
Hi ,
I have been trying to use the LDAP authetnication 
and getting errors!!
I am stuck at this..after adding this code ..Entering any username and password authenticates and gives admin priveledges
i am using pro version and all the default kibana users are there

```yml
   - name: "test"
      ldap_auth:
            name: "ldap2"
            groups: ["g3"]
      type: allow
      kibana_access: rw
      indices: ["xxx"]
      kibana_hide_apps: ["readonlyrest_kbn", "timelion", "readonlyrest", "kibana:dev_tools", "kibana:management"]

    ldaps:

    - name: ldap2
      host: "xx.xxxx.com"
      port: 389
      bind_dn: "cn=xxxxx,dc=xxxx,dc=com"
      bind_password: "xxxx"
      search_user_base_DN: "dc=xxxxx,dc=com"
      user_id_attribute: "uid"
      search_groups_base_DN: "ou=Groups,dc=xxxx,dc=com"
      connection_pool_size: 30                                  # optional, default 30
      connection_timeout_in_sec: 30                             # optional, default 1
      request_timeout_in_sec: 30                                # optional, default 1
      cache_ttl_in_sec: 60
      unique_member_attribute: "uniqueMember"

```

**Comment by sscarduzio** [comment]
Hello @shubhamverma27,
Can you provide the ES logs showing the request getting through with admin privileges?

Also, please share the missing parts of the above ES elasticsearch.yml, starting with the "readonlyrest: " key.

Have you configured the kibana.yml too as per instructions?

readonlyrest.com/documentation/kibana.html

**Comment by shubhamverma27** [comment]
readonlyrest:

     # IMPORTANT FOR LOGIN/LOGOUT TO WORK
    prompt_for_basic_auth: false
 
response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin
    access_control_rules:

    - name: "::LOGSTASH::"
      auth_key: logstash:logstash
      actions: ["indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create"]
      indices: ["logstash-*"]

    - name: "::KIBANA-SRV::"
      auth_key: kibana:kibana

    - name: "::RO::"
      auth_key: xx:dev
      kibana_access: ro
      indices: [ ".kibana", ".kibana-devnull", "bsg"]
      kibana_hide_apps: ["readonlyrest_kbn", "timelion", "kibana:dev_tools", "kibana:management"]

    - name: "::RW::"
      auth_key: clas:dev
      kibana_access: rw
      indices: [".kibana", ".kibana-devnull", "clas"]
      kibana_hide_apps: ["readonlyrest_kbn", "timelion", "readonlyrest", "kibana:dev_tools", "kibana:management"]


    - name: "::ADMIN::"
      auth_key: admin:dev
      # KIBANA ADMIN ACCESS NEEDED TO USE THE ROR KIBANA APP!
      kibana_access: admin

    - name: "::WEBSITE SEARCH BOX::"
      indices: ["public"]
      actions: ["indices:data/read/*"]

    - name: "::Shubham::"
      kibana_access: rw
      indices: [".kibana", ".kibana-devnull", 'creditum']
      kibana_hide_apps: ["readonlyrest_kbn", "timelion", "readonlyrest", "kibana:dev_tools", "kibana:management"]
      auth_key: xxx:dev



here it is 
after this code the ldap code is there

**Comment by sscarduzio** [comment]
OK without seeing any error logs .. I already see an issue in the settings:

```
 - name: "test"
      ldap_auth:
            name: "ldap2"
            groups: ["g3"]
      type: allow
      kibana_access: rw
      indices: ["xxx"]
      kibana_hide_apps: ["readonlyrest_kbn", "timelion", "readonlyrest", "kibana:dev_tools", "kibana:management"]
```
In a rules block that includes `kibana_access` , when you have a `indices` rule, always include ".kibana", ".kibana-devnull" indices as well.
