### ISSUE TITLE
Password issues

### ISSUE THREAD

**Issue by immort4tor** [sscarduzio/elasticsearch-readonlyrest-plugin#243]
Hi, there are problems when authorizing (ldap) users whose password contains characters:
":"  ";"  "," "." and so on

**Comment by ld57** [comment]
Hi @immort4tor ,

thansk for the feedback.

also, I saw that you are working with a Microsoft AD.

by luck, were you able to test authentication and authorization by group membership ?
Does it work on your side ? ( I can authenticate with user directly in OU, but test with the user in AD group does not give me success.

I have some trouble in my tests...

**Comment by immort4tor** [comment]
Hi, show your config with ldap section

**Comment by ld57** [comment]
here the ldaps config

```
    ldaps:

    - name: srvldap
      host: "srvldap.root.corp"
      port: 389
      ssl_enabled: false
      ssl_trust_all_certs: true
      bind_dn: "CN=elk_account_ldap,OU=Service_Account,DC=srvldap,DC=root,DC=corp"
      bind_password: "pouetpouet"
      search_user_base_DN: "OU=ELK,OU=LAB,DC=srvldap,DC=root,DC=corp"
      user_id_attribute: "sAMAccountName"
      search_groups_base_DN: "OU=ELK,OU=LAB,DC=srvldap,DC=root,DC=corp"
      unique_member_attribute: "member"
      connection_pool_size: 10
      connection_timeout_in_sec: 10
      request_timeout_in_sec: 10
      cache_ttl_in_sec: 60      
```

and here my RoR block : 

```
    - name: elkg test LAB (read)
      ldap_authentication: "srvldap"
      ldap_authorization:
        name: "srvldap"
        groups: ["L_elkg_test_vcsa6_R"]
      type: allow
      kibana_access: ro
      indices: ["<no-index>", "watcher", "watcher_alarms", ".kibana*", "log_lu_ei_sys_vcsa6*", "home"]
```

Cases : 
if using a user toto stored in the OU=ELK,OU=LAB,DC=srvldap,DC=root,DC=corp , it works
if using a user toto stored in an another OU, but is member of the group L_elkg_test_vcsa6_R , it does not work.

here the ldap browsing of the group object, when toto is member of group, but user is in another OU : 
`member: CN=Toto the BestGuy,OU=Test_purpose,OU=Department13,OU=Standards,OU=Users,DC=srvldap,DC=root,DC=corp
`
also, login username is toto.t

**Comment by ld57** [comment]
Oh geez.... just saw something....

in fact, RoR ldap query the group, get members, and rerun the ldap query against user search... 

am I right ?

**Comment by ld57** [comment]
ah , the response is log is ldap_authentication->False

`[2017-06-28 17:14:41,653][INFO ][plugin.readonlyrest      ] [ELKG_TEST] forbidden request: { ID:1101880356-1750295182, TYP:MultiGetRequest, USR:toto.t(?), BRS:true, ACT:indices:data/read/mget, OA:127.0.0.1, IDX:.kibana, MET:POST, PTH:/_mget, CNT:<OMITTED, LENGTH=62>, HDR:accept,accept-encoding,accept-language,authorization,connection,content-length,content-type,cookie,host,kbn-version,referer,user-agent,x-forwarded-for,x-forwarded-port,x-forwarded-proto, HIS:[Kibana Server (we trust this server side component, full access granted via HTTP authentication)->[auth_key->false]], [Logstash can write and create its own indices->[auth_key->false]],[Dummy (to permit request for basic authentication popup)->[auth_key->false]], [elkg test LAB (read)->[ldap_authentication->false, kibana_access->true, indices->true]] } Reason: null (null)
`

**Comment by ld57** [comment]
Ok I may find my issue by rereading your RoR ldaps config in your other post in #234 .

I forgot to add the groups in authentication section too...
retesting

**Comment by ld57** [comment]
mmhh same result with

    - name: elkg test LAB (read)
      ldap_auth: 
        name: "srvldap"
        groups: ["L_elkg_test_vcsa6_R"]
      type: allow
      kibana_access: ro
      indices: ["<no-index>", "watcher", "watcher_alarms", ".kibana*", "log_lu_ei_sys_vcsa6*", "home"]

**Comment by immort4tor** [comment]
is there any users in 
"OU=ELK,OU=LAB,DC=srvldap,DC=root,DC=corp"
or only service account? try set "DC=srvldap,DC=root,DC=corp"

**Comment by ld57** [comment]
I have no user in "OU=ELK,OU=LAB,DC=srvldap,DC=root,DC=corp" except the service account.

but if I set set search_user_base_DN: "DC=srvldap,DC=root,DC=corp" , will it not let everybody in AD getting access to ELK ?

I m going to test this and will give feedback

**Comment by ld57** [comment]
Hi, I confirm, all users in ldap match the block with this modification...

here my RoR block : 

```
    - name: elkg test LAB (read)
      ldap_authentication: "srvldap"
      ldap_authorization:
        name: "srvldap"
        groups: ["L_elkg_test_vcsa6_R"]
      type: allow
      kibana_access: ro
      indices: ["<no-index>", "watcher", "watcher_alarms", ".kibana*", "log_lu_ei_sys_vcsa6*", "home"]
```

```
    ldaps:

    - name: srvldap
      host: "srvldap.root.corp"
      port: 389
      ssl_enabled: false
      ssl_trust_all_certs: true
      bind_dn: "CN=elk_account_ldap,OU=Service_Account,DC=srvldap,DC=root,DC=corp"
      bind_password: "pouetpouet"
      search_user_base_DN: "DC=srvldap,DC=root,DC=corp"
      user_id_attribute: "sAMAccountName"
      search_groups_base_DN: "OU=ELK,OU=LAB,DC=srvldap,DC=root,DC=corp"
      unique_member_attribute: "member"
      connection_pool_size: 10
      connection_timeout_in_sec: 10
      request_timeout_in_sec: 10
      cache_ttl_in_sec: 60      

```

I had in mind to obtain this behavior : 
Users belonging to group L_elkg_test_vcsa6_R (CN=L_elkg_test_vcsa6_R,OU=ELK,OU=LAB,DC=srvldap,DC=root,DC=corp) would only match to the block, and gets access to kibana ro, indices "<no-index>", "watcher", "watcher_alarms", ".kibana*", "log_lu_ei_sys_vcsa6*", "home" etc.

Currently the group has no member now, and all users in ldaps srvldap are able and match the block..

what did I do wrong ? How did you manage access on your side ?
