### ISSUE TITLE
Kibana in RED status after ROR install

### ISSUE THREAD

**Issue by askids** [sscarduzio/elasticsearch-readonlyrest-plugin#264]
i installed ROR plugin readonlyrest-1.16.10_es5.5.1 for Elasticsearch 5.5.1 running on windows 2008 R2. I added the below entries to elasticsearch.yml file and restarted the Elasticsearch service. When I launched the new https ES endpoint in chrome, i was prompted for id/pwd and entering the kibana id/pwd worked. Then I modified the kibana.yml file and uncomment elasticsearch.username and elasticsearch.password and added id/pwd, updated the elasticsearch.url property to use the https endpoint. Restarted Kibana. 

But Kibana is showing status in red with error message. Unable to connect to Elasticsearch at https://xxxxxxxx.yyyyyyyyy.com:12200. Its red for plugin:elasticsearch@5.5.1, ui settings, plugin:xpack_main@5.5.1, plugin:searchprofiler@5.5.1, plugin:tilemap@5.5.1, plugin:ml@5.5.1.

Kibana is running on same machine, but different port. Am I missing any steps for updating kibana.yml file? 

```
#
# ReadonlyREST entries
http.type: ssl_netty4
readonlyrest:
    enable: true 
    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin
    
    ssl:
      enable: true
      # put the keystore in the same dir with elasticsearch.yml 
      keystore_file: "plugins/readonlyrest/mykeystore.jks"
      keystore_pass: Password1
      key_pass: Password1
   
    access_control_rules:

    - name: Kibana Server
      type: allow
      auth_key: kibana:kibana
      verbosity: error
```

Thanks!
