### ISSUE TITLE
elasticsearch not starting with plugin configuration

### ISSUE THREAD

**Issue by nreese** [sscarduzio/elasticsearch-readonlyrest-plugin#28]
I have successfully installed readonlyrest plugin version 1.7 into an elasticsearch 2.2 instance. I can start elasticsearch and verify that the line 'plugins[readonlyrest]' is contained in the elasticsearch log file.

However, if I start to configure readonlyrest plugin in /etc/elasticsearch/elasticsearch.yml file, elasticsearch does not start and elasticsearch.log file never gets created. Below is my configuration. 

```
readonlyrest:
    enable: true
    access_control_rules:

    - name: Accept only GETs with empty body from other host
      type: allow
      methods: [GET]
      maxBodyLength: 0
```
What am I doing wrong? Is there a way to get more verbose logging?

Thanks,

Nathan
