### ISSUE TITLE
Not able to create index from a remote system via logstash using "csv filter plugin".

### ISSUE THREAD

**Issue by sukeshtest** [sscarduzio/elasticsearch-readonlyrest-plugin#294]
I am not able to create index from a remote system (192.168.1.142) via logstash using "csv filter plugin".
Iam getting the error,
`FORBIDDEN by default req={ ID:1454358066-1489483709#141, TYP:GetIndexTemplatesRequest, CGR:N/A, USR:[no basic auth header], BRS:true, ACT:indices:admin/template/get, OA:10.65.226.142, IDX:<N/A>, MET:HEAD, PTH:/_template/ec2_utilizationv2, CNT:<N/A>, HDR:Accept-Encoding,Connection,content-length,Content-Type,Host,User-Agent, HIS:[Accept requests from users in group support_group->[hosts->true, methods->false]], [Accept requests from users in group readonly_group->[methods->false, hosts->true]], [full access to internal servers->[hosts->false]] }`
```
I am able to push the data if I create the index manually.
readonlyrest configuration is 
readonlyrest:
    enable: true
    response_if_req_forbidden: Sorry, your request is forbidden
    # Default policy is to forbid everything, let's define a whitelist
    access_control_rules:

    # from these IP addresses, accept any method, any URI, any HTTP body
    - name: full access to internal servers
      type: allow
      hosts: [127.0.0.1]

    - name: Accept requests from users in group radmin
      type: allow                       
      hosts: [192.168.1.0/24, 192.168.5.0/24, 192.168.7.0/24]
      methods: [OPTIONS,GET,PUT,DELETE,POST]
```
