### ISSUE TITLE
Elasticsearch 6.1.0 throws when readonlyrest settings are added to elasticsearch.yml

### ISSUE THREAD

**Issue by trondhindenes** [sscarduzio/elasticsearch-readonlyrest-plugin#301]
We've been running the following readonlyrest settings in elasticsearch 6.0.0 for a while now, and its been working great. However, the same settings used in ES 6.1.0 throws an exception. If I remove the ror settings below from config, everything seems to be working:

Here's the Elasticsearch exception I'm getting:
`Exception in thread "main" SettingsException[Failed to load settings from [elasticsearch.yml]]; nested: IllegalStateException[only value lists are allowed in serialized settings]`
```
readonlyrest:
    audit_collector: true

    external_authentication_service_configs:
      - name: elasticsearch_auth
        authentication_endpoint: "https://stuff.stuff/api/auth"
        success_status_code: 200
        cache_ttl_in_sec: 60
```
