### ISSUE TITLE
Setting up with Kibana 4 ?

### ISSUE THREAD

**Issue by nitram4** [sscarduzio/elasticsearch-readonlyrest-plugin#31]
can it be used with kibana 4 and basic http auth ending up with multiple users with multiple ACL accessing thru Kibana 4?
thanks

**Comment by sscarduzio** [comment]
I don't see why not, you could have a rule per user/access level like this:
```yml
readonlyrest:
    enable: true
    response_if_req_forbidden: <h1>Forbidden</h1>    
    access_control_rules:

    - name: Sales login
      type: allow
      indices: [sales-index, public-index]
      auth_key: sales:passwd1

    - name: Admin login
      type: allow
      indices: [accounts-index, sales-index, public-index]
      auth_key: admin:passwd2
```

Have a try and let me know.

**Comment by sscarduzio** [comment]
Hey @nitram4: I've tested what you asked, and  I understood that isolating what users can see in Kibana  is not as trivial as I thought. But the good news is if all you want is a few distinct logins in Kibana, that's super easy! 

### Multiple login to the same Kibana dashboards (no index isolation)
In this scenario, the Kibana Node.js server logs in the same way browsers do: HTTP Basic Auth. We created a username and password for it too. 
```yml
readonlyrest:
    enable: true
    response_if_req_forbidden: <h1>Forbidden</h1>    
    access_control_rules:

    - name: Kibana Server
      type: allow
      auth_key: server:1234567890

    - name: User1 login
      type: allow
      auth_key: user1:passwd1

    - name: User2
      type: allow
      auth_key: user2:passwd2
 ```
The two users will see identical dashboards inside Kibana.

**PS**: Don't forget to add these two properties on the kibana side  ( edit `conf/kibana.yml`)
```yml
  elasticsearch.username: server
  elasticsearch.password: 1234567890
```

Now point your browser to Kibana and you should be asked username and password. 
Insert credentials either for User1 or User2 and you're in.

I hope it helps!

_S

**Comment by danielmotaleite** [comment]
I'm also having problems setting up this with kibana. ES direct access works fine.

If i try to login with a readonly user (only GET) , it fails because it is needing sending POST requests:

```
Request URL:https://kibana.site.com/elasticsearch/_mget?timeout=0&ignore_unavailable=true&preference=1459269385442
Request Method:POST
```
this fails in this config

```
    - name: Accept user-ro user.
      type: allow
      methods: [GET]
      auth_key: user-ro:password
```

adding the POST method and adding the  `indices: [logstash-*-user-ro]` to avoid users to overwrite dashboards, it also fails, from the ES log i see

```
Mar 29 18:27:15 ES1 elasticsearch[29397]: [2016-03-29 18:27:15,988][DEBUG][plugin.readonlyrest.acl.blocks.rules.impl] This request uses the index 'null' which is not in the list.
Mar 29 18:27:15 ES1 elasticsearch[29397]: [2016-03-29 18:27:15,988][DEBUG][plugin.readonlyrest.acl  ] [Accept user-ro user.] request matches no rules, forbidden by default: req: /_mget?timeout=0&ignore_unavailable=true&preference=1459268072486 - method: POST - origin addr: 192.168.0.10
```
adding  `indices: [logstash-*-user-ro,null]` will not work

So is there any way of doing this?
my objective is first to protect the kibana dashboards and then later (if possible) restrict some indices to some users

So to start, maybe adding code to check the special "null" index requests to workaround those requests without any indices.

For blocking the GET/POST, kibana seems to need the POST for almost anything, so may be better to check for urls

from what i see, creating dashboards are like this:

```
 [Accept all requests from localhost/localnet.] request matches no rules, forbidden by default: req: /.kibana/dashboard/Testes2?op_type=create - method: POST - origin addr: 192.168.0.10
```
overwrite tries the same, gets 409 conflict and then the browse ask the user if they are sure to overwrite and it sends
```
 [Accept all requests from localhost/localnet.] request matches no rules, forbidden by default: req: /.kibana/dashboard/Testes2 - method: POST - origin addr: 192.168.0.10
```
visualizations are the same rules:
```
 request matches no rules, forbidden by default: req: /.kibana/visualization/CPU-usage-per-process2?op_type=create
```
So as in saved search
```
request matches no rules, forbidden by default: req: /.kibana/search/trash?op_type=create
```

So i would say that .kibana is a special index and that  anything that is `/.kibana/[^/]*/[^?]*?op_type=create` is a CREATION rule, `/elasticsearch/.kibana/[^/]*/[^?]*$` is OVERWRITE rule.

can we use the` uri_re:` to create rules for this? how many `uri_re` can we use in the config

Sorry for the long post

**Comment by sscarduzio** [comment]
Thanks for the detailed report, it does remind me a lot of the struggles I had last weekend.
I must say it’s quite a complex product which requires a lot of attention in order to be safely exposed in read only mode. But eventually I won :)
I’ll release very soon some new rule that are Kibana specific that will most likely solve all these issues.

**Comment by danielmotaleite** [comment]
Great news!! Thank you very much! :D

until then, i just tested this and it seems to work (not perfect, i don't really know if HEAD is needed and if i should also add the PUT):

```
    - name: Accept kibana access.
      type: allow
      methods: [GET,HEAD]
      uri_re: ^/.kibana/[^?]*$

    - name: Accept test user.
      type: allow
      methods: [GET,POST,HEAD]
      auth_key: test:password
      uri_re: ^/(_.*|logstash-.*-test.*|.kibana/[^?]*\?op_type=create)$

    - name: Forbit overwrite in kibana.
      type: forbid
      methods: [POST]
      uri_re: ^/.kibana/[^?]*$

```

But until the new versions is released, this should be enough

Again, thanks!

**Comment by danielmotaleite** [comment]
actually, after asking the password several times, it manage to overwrite a dashboard... that is weird how it manage to do that...

how the rules work? it will stop on the first that match, or it will match all rules the the last result is the one valid? do the rule ordering even change how things work?

**Comment by sscarduzio** [comment]
The evaluation stops at the first block (block = sets of rules) where all the rules match. The blocks are evaluated in the order they appear in the configuration file.
I think `uri_re` is a bit too hacky and the guarantees it offers are quite brittle after all. That’s why I introduced real indices matching rules, and that’s why yesterday I made the `kibana_action`rule.
This new rule basically checks the request “action” field matches any of the ones defined in the official Shield recommended configuration:

https://www.elastic.co/guide/en/shield/current/kibana.html <https://www.elastic.co/guide/en/shield/current/kibana.html>

I will commit it later today so you can test it.

**Comment by sscarduzio** [comment]
Can you try this build? I built it for ES 2.2.1, I assume you had this because it's the latest.
https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/blob/master/download/elasticsearch-readonlyrest-v1.9.0_es-v2.2.1.zip?raw=true

Example configuration
```yml

readonlyrest:
    enable: true

    response_if_req_forbidden: <h1>Forbidden</h1>
    
    access_control_rules:

    - name: browser
      type: allow
      auth_key: user:pass
      kibana_access: ro

```

Configure Kibana 4 to use these credentials as well (or whitelist the Kibana server's IP, up to you) and then try to connect to Kibana with the browser. You'll be asked for a login and you won't be able to create dashboards or anything else.

You can create another user with write permission copy-pasting the same rule block but with `kibana_access: rw`.

**Comment by danielmotaleite** [comment]
tested and works perfectly! MANY THANKS!! :smile: 

i could even manage to build a config to allow one to save NEW search/visualization/dashboards, but denies delete and overwrites using this:

```
    - name: Allow NEW saves user.
      type: allow
      methods: [POST]
      auth_key: user:pass
      uri_re: ^/.kibana/.*\?op_type=create$

    - name: Allow semi-read-only user.
      type: allow
      methods: [GET,POST,HEAD]
      auth_key: user:pass
      kibana_access: ro
```
Of course, the ideal solution would be create a "kibana_access: ro-except-new-saved-objects" ;)

Anyway, with this i can give users access without having afraid for then to remove things

i'm going now to play with the indices lock, to see if they work too

**Comment by sscarduzio** [comment]
Glad it helped, thanks for testing it! 
Maybe you're right with proposing the third state (something like "ro+") would be useful, but here's the catch: the ".kibana" index name is just a default that people can change from `conf/kibana.yml`.

Then we should let people also tell us what's the name of their kibana index. How do you think an intuitive configuration would look like?

The only one that comes to my mind, I don't like because I'd avoid nesting properties, something like this for example:
```yml
    - name: Allow NEW saves user. # PSEUDO CONF DON'T COPY PASTE! 
      type: allow
      kibana: 
        access: ro
        conf_index: [.kibana, .kibana-devnull]  
      auth_key: user:pass
```
Looks way too complex and adds new unnecessary vocabulary that confuses the user. It's also very conf-error prone: people are already (rightfully) reporting bugs that ends up being indentation errors.
 
To be honest, if we manage to create a simple example where we achieve the wanted result with 2 blocks of old rules instead of one with combo-rules it's a small victory.

I'd like to talk again about this use case once the indices wild cards are implemented :)
