### ISSUE TITLE
_cat/templates API returns blank list

### ISSUE THREAD

**Issue by fbaligand** [sscarduzio/elasticsearch-readonlyrest-plugin#311]
Hi,

Since I install readonlyrest (v1.16.15) on my elasticsearch cluster (v5.6.3), The elasticsearch API `GET _cat/templates` does not work : it returns an empty list, although I have 2 templates installed.
And I can confirm it, because I get these 2 templates using `GET _template` API.

=> Could you fix readonlyrest so that `_cat/templates` API works as expected (returns the existing templates list) ?

**Comment by sscarduzio** [comment]
just tried in 6.1,  it works. Will try with older ES.

```
$ curl  -s  -k  "https://localhost:9200/_cat/templates" -H'content-type:application/json' -u kibana:kibana
template1 [te*, bar*] 0
```

**Comment by sscarduzio** [comment]
I just tried in 5.6.3, same result:
```
$ curl  -s  -k  "https://localhost:9200/_cat/templates" -H'content-type:application/json' -u kibana:kibana
template1 te* 0
```
Maybe share your settings?

**Comment by fbaligand** [comment]
Hi @sscarduzio,

Thank for your answer and your first tests !

My readonlyrest configuration is very simple :
```
# READONLYREST SECURITY CONFIGURATION
readonlyrest:
    access_control_rules:
    - name: "Allow anything"
      actions: ["*"]
      indices: ["*"]
```

Did I miss something ?
