### ISSUE TITLE
Redundant users/groups/proxy_auth & broken link

### ISSUE THREAD

**Issue by seanziee** [sscarduzio/elasticsearch-readonlyrest-plugin#316]
I've listed my config below for my nginx -> ROR -> ES setup. I'm trying to understand the relationship between users, groups and proxy_auth because it seems redundant. The docs mentions to see "User Management" but that link is dead. [See here](https://github.com/beshu-tech/readonlyrest-docs/blob/9143827060412a0ffc080e460272d73924c7d849/elasticsearch.md#authentication). So I'm a bit lost. I have a user being forwarded into ROR from NGINX. To give the user access control, do I need to define both users and then reference that `username` in the access control rules' `proxy_auth` (or do i set the `proxy_auth` in both to be the array of users?)? When I remove the users section entirely and add the nginx users into `proxy_auth: ["<here>"]`, I get errors. 

What is the best way to set this up?

```
readonlyrest:
  enable: true
  response_if_req_forbidden: Sorry, your request is forbidden.
  access_control_rules:
  - name: HQ Admins
    type: allow
    groups: ["HQ_Admin"]
    proxy_auth: ["admin"] 
    indices: ["*"]

  - name: Client ReadOnly
    type: allow
    kibana_access: rw
    groups: ["HQ_Ro"]
    proxy_auth: ["*"] 
    indices: [".kibana_@{X-Forwarded-User}", ".kibana_public"]

  - name: "::KIBANA-SRV::"
    type: allow
    auth_key: kibana:kibana

  users:

  - username: admin
    proxy_auth: ["admin"]         
    groups: ["HQ_Admin"]

  - username: client
    proxy_auth: ["a", "apple"]
    groups: ["HQ_Ro"]
```
