### ISSUE TITLE
Can't login with LDAP on Kibana with Kibana RoR Compagnon

### ISSUE THREAD

**Issue by barryib** [sscarduzio/elasticsearch-readonlyrest-plugin#329]
I updated our ES cluster and RoR today to ES 5.6.8 and RoR 1.16.18.

Since then, I can't login in Kibana. In Elasticsearch logs, I can see that the ldap's user is correctly authenticate and authorized because its matching this rule:

```yml
      name: Allow anything from ad-app-es-admin group
      kibana_access: admin
      ldap_authentication: "ldap_ad"
      ldap_authorization:
        name: "ldap_ad"
        groups: ["ad-app-es-admin"]
```

In my network tab on chrome, I can see that I'm getting correctly logged in, before getting redirected to `logout`.

Here is my kibana configuration:

```yml
elasticsearch.password: secure_password
elasticsearch.url: http://localhost:9200
elasticsearch.username: kibana_server
logging.dest: /var/log/kibana/kibana.log
readonlyrest_kbn.cookiePass: xxxxxxxxxxxxxxxxxxx
readonlyrest_kbn.proxy_auth_passthrough: false
request_timeout: 120000
server.host: 0.0.0.0
server.port: 5601
```

I'm my missing something? Everything was working fine on 1.16.14. I'm running RoR Kibana Entreprise 1.16.18

**Comment by barryib** [comment]
More info, there is no username defined in cookie (`username=`)

**Comment by sscarduzio** [comment]
Hi @barryib!
You're the second person reporting this, I could not reproduce it on my own. I suspect there is something going on with the identity injection process.
I will need to give you a debug log build.

**Comment by barryib** [comment]
Be my guest.

**Comment by barryib** [comment]
Closing this. It was a configuration issue.

In fact, ldap users were matching by this rule **Allow monitoring from localhost and LB without auth** because it's comming from Kibana which is installed on each ES node (localhost as elasticsearch.url).

```yml
name: Allow monitoring from localhost and LB without auth
verbosity: error
hosts:
  - 127.0.0.1
  - XX.XXX.XXX.XXX/30
actions:
  - cluster:monitor/*
  - indices:monitor/*

name: Allow anything from ad-app-es-admin group
kibana_access: admin
ldap_authentication: "ldap_ad"
ldap_authorization:
  name: "ldap_ad"
  groups: ["ad-app-es-admin"]
```

Rule order is **VERY** important !!!
