### ISSUE TITLE
Adding multiple group permissions to a user

### ISSUE THREAD

**Issue by sahil-sharma** [sscarduzio/elasticsearch-readonlyrest-plugin#339]
Hello, I am facing an issue:

Environment:
OS: Ubuntu:14.04
ES version: 5.6.7
ReadOnlyRest version: 1.16.18
Cerebro plugin version: 0.7.3

Created 4 indices (clienta1, clienta2, clientb1, clientb2).

ReadOnlyRest YAML config:
```yml
readonlyrest:
  
  enable: true
  response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin

  access_control_rules:

  - name: "Accept requests from users in group team1 on clienta1"
    type: allow
    groups: ["team1"]
    indices: ["clienta1"]
    verbosity: info

  - name: "Accept requests from users in group team2 on clienta2"
    type: allow
    groups: ["team2"]
    indices: ["clienta2"]
    verbosity: info

  - name: "Accept requests from users in group team3 on clientb1"
    type: allow
    groups: ["team3"]
    indices: ["clientb1"]
    verbosity: info

  - name: "Accept requests from users in group team4 on clientb2"
    type: allow
    groups: ["team4"]
    indices: ["clientb2"]
    verbosity: info

  users:  
  
  - username: user1
    auth_key: user1:demo1
    groups: ["team1"]
    verbosity: info

  - username: user2
    auth_key: user2:demo2
    groups: ["team2"]
    verbosity: info

  - username: user3
    auth_key: user3:demo3
    groups: ["team3"]
    verbosity: info

  - username: user4
    auth_key: user4:demo4
    groups: [ "team4" ]
    verbosity: info

  - username: user5
    auth_key: user5:demo5
    groups: [ "team1", "team2" ]
    verbosity: info

  - username: user6
    auth_key: user6:demo6
    groups: [ "team3", "team4" ]
    verbosity: info

  - username: lastuser
    auth_key: lastuser:lastuser
    groups: ["team1", "team2", "team3", "team4"]
    verbosity: info`
```
Able to see individual user can see respective indices. But user5 can access clienta1 and clienta2. Similarly user6 can access clientb1 and clientb2 and lastuser can access clienta1/a2/b1/b2.

But I am seeing that user5 can only see clienta1 not the clienta2. And, user6 can see clientb1 but not clientb2. And, lastuser can see only clienta1 but not the clienta2/b1/b2.
User5:
![user5](https://user-images.githubusercontent.com/5774379/38974419-a96f4c78-43c7-11e8-8c0e-4408ea815a50.png)
User6:
![user6](https://user-images.githubusercontent.com/5774379/38974424-b1c34762-43c7-11e8-9b4b-950d01781533.png)
Lastuser:
![lastuser](https://user-images.githubusercontent.com/5774379/38974425-b5a022a6-43c7-11e8-8021-61603638ebd7.png)

My understanding is there is no such provision to assign a user an access to multiple groups.
Please correct me if I am mistaken.
Looking forward to see your reply on this.
Thank you!
