### ISSUE TITLE
accept_x-forwarded-for_header: true, but no difference?

### ISSUE THREAD

**Issue by sindarina** [sscarduzio/elasticsearch-readonlyrest-plugin#34]
I have an ES instance behind nginx, as a TLS proxy, but ES with plugin still sees everything as coming from localhost, even with `accept_x-forwarded-for_header: true` and proxy passing the header;

```
# Forward all requests to the local ES instance
location / {
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_pass http://127.0.0.1:9200/;
}
```
Plugin is active, and if I set `auth_key` the request is rejected, so the plugin does work.

Is there something that I am missing? A way to debug what the plugin actually sees, in terms of headers? ES 2.2.1 with current master of the plugin.

**Comment by sindarina** [comment]
I know setting the header can work, because I can set `X-API-Key` in the nginx config and have that work, but `X-Forwarded-For` remains elusive. I'll probably do access control within nginx instead.

**Comment by sscarduzio** [comment]
Can you share the configuration file you're using?

I just tested this and it works nicely :
```yml
readonlyrest:
    enable: true
    response_if_req_forbidden: <h1>Forbidden</h1>
    access_control_rules:
    - name: xfwd4
      type: allow
      hosts: [6.6.6.6]
      accept_x-forwarded-for_header: true
```

Called it like this:
```
curl -X GET  -H "X-Forwarded-For: 6.6.6.6"  "http://localhost:9200/idx"
```
