### ISSUE TITLE
Authentication with Apikey

### ISSUE THREAD

**Issue by haversham13** [sscarduzio/elasticsearch-readonlyrest-plugin#347]
Hello, I'm using ROR in order to give only read-only rights on one index for the user who are not in the internal network. Users from the internal network should have all rights. So, external users must be authenticated in order to use ES. These users have an Apikey which is used to be authenticated, I want to use external authentication for this purpose. Is it possible to do external authentication with Apikey?

For this purpose, I tried to do something like that:

readonlyrest:
    response_if_req_forbidden: Sorry, your request is forbidden.   
    access_control_rules:

    - name: Accept all requests from localhost, and internal network
      hosts: ["127.0.0.1","10,185.0.1/16"]

    - name: Just certain indices, and read only
      methods: GET
      actions: ["indices:data/read/*"]
      indices: ["example-*"]
      external_authentication: "ext1"

external_authentication_service_configs:
    - name: "ext1"
      authentication_endpoint: "http://localhost:5000/apiauth"
      success_status_code: 200
      cache_ttl_in_sec: 3600

I pass the Apikey in the header with 'Authorization'. But, maybe it's with 'X-API-Key'. But I think it isn't possible to do that. I tried to look at the code to know if it's implemented but I didn't found it. 

One possibility is to use a reverse proxy to do the authentication to filter the requests or I'm wrong. My constraint is to use Apache as a reverse proxy. 
Thank you for helping me.

**Comment by rbkasat** [comment]
@sscarduzio I think he is asking about external_authentication_service_configs, my pull request was for group service provider [more of authorization than authentication problem].

He might need to look into "external_authentication_service_configs", but yes its similar work in a different rule and will be easy enough.

@haversham13 one trick you can try,
https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#dynamic-variables
eg:
external_authentication_service_configs:
- name: "ext1"
   authentication_endpoint: @{x-nginx-user}
   success_status_code: 200
   cache_ttl_in_sec: 3600

so when you forward request to ES forward an header "x-nginx-user" which will have token already embeded. eg: for basicauth   https://user:pass@http://localhost:5000/apiauth

**Comment by haversham13** [comment]
Thank you, both, for your fast reply.

@rbkasat  so in order to use dynamic variables we need a proxy which injects header and then the external authentication rule of ror is applied, right? I think it's not really useful in my case because users who have a valid API key have the right to query ES. So, I want to validate the key and not to know who that person is. 

I have a database where all API keys are stored. I also have an API which checks if the API key is valid or not and sends an http responds 200 if it's valid.  Let's if I query ES with 
curl -X GET 'http://example:9200/testindex/_search' -H "apikey:b9ce69cc77f48"       

and I have something like this:
external_authentication_service_configs:

    name: "ext1"
    authentication_endpoint: "http://localhost:5000/apiauth?@{apikey}"
    success_status_code: 200
    cache_ttl_in_sec: 3600

Is it possible to retrieve the header like this without going through a proxy?

**Comment by haversham13** [comment]
Greetings, I think that my question isn't clear so I'll try to clarify it.

I'm implementing ES with the readonlyrest free plugin and I want to rely on an external API to authenticate my users. The API includes a /authenticate entry point that takes a SHA256 value from the HTTP Header 'Authorization' as an API key.

**To implement my use case, I considered this one from the README documentation 'External Basic HTTP Authentication' as a starting point:**

https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin#use-case-external-basic-http-authentication

My readonlyrest.yml file contains the following rules:

```
readonlyrest:
  response_if_req_forbidden: Sorry, your request is forbidden.

  access_control_rules:
    - name: Accept all requests from localhost
      hosts: ["127.0.0.1"]

    - name: "Allow user using external authentication"
      methods: GET
      actions: ["indices:data/read/*"]
      indices: ["example-*"]
      external_authentication: "ext1"

  external_authentication_service_configs:
    - name: "ext1"
      authentication_endpoint: "http://localhost:5000/apiauth"
      success_status_code: 200
      cache_ttl_in_sec: 3600
```

I'm not using a reverse proxy at the moment, this is to ensure that this simple configuration is working.

When I look at the Authentication API log, no request is received from the readonlyrest plugin.

**Thus, could you please let me know if the following assumption are correct (and if not, correct them):**

- when I issue an Elasticsearch request, the plugin will contact http://localhost:5000/apiauth and forward the Authorization HTTP Header to the Authentication endpoint.
- If the Auth endpoint returnrs a status code 200, Elasticsearch will serve the request. Otherwise, the requested is dropped due to authentication failure

In case my assumptions are correct, I don't think I need dynamic variables in this case.

Thank you very much for your help !

**Comment by sscarduzio** [comment]
Hi @haversham13, are you are not matching the first block with your tests? Please show us the ES logs, so we can observe the ACL evaluation history for your request.

**Comment by haversham13** [comment]
Here are some tests which I made until now,
With plugin disabled, I have access to everything
With plugin enabled and no access rules, everything is blocked.
Allow everything works. **Replaced with Allow - Accept all requests from localhost**
```
- name: Allow everything
   type: allow
```
**Allow - Accept all requests from localhost**
```
- name: Allow  Accept all requests from localhost
      hosts: ["127.0.0.1"]
```
**For test purposes, I disabled the first Allow rule. My ACL looks like this**
```
- name: "Allow user using external authentication"
      methods: GET
      actions: ["indices:data/read/*"]
      indices: ["example-*"]
      external_authentication: "ext1"

  external_authentication_service_configs:
    - name: "ext1"
      authentication_endpoint: "http://localhost:5000/apiauth"
      success_status_code: 200
      cache_ttl_in_sec: 3600
```
I used a simple curl command to test:
curl -X GET --header "Authorization:<sha256>"  http://example:9200/example/_search" 

**Logs**
```
[2018-05-07T13:37:42,280][DEBUG][t.b.r.a.ACL        ] checking request:2090974056-422413208#1246                                                                                                               
[2018-05-07T13:37:42,280][DEBUG][t.b.r.a.b.r.i.ExternalAuthenticationAsyncRule] Basic auth header not present!                                                                                                       
[2018-05-07T13:37:42,280][DEBUG][t.b.r.a.b.Block          ] [Allow read access to Androzoo user on indice apkfiles]
 the request matches no rules in this block: { ID:2090974056-422413208#1246, TYP:MainRequest, CGR:
	N/A, USR:[no basic auth header], BRS:false, KDX:null, ACT:cluster:monitor/main, OA:127.0.0.1, 
	DA:127.0.0.1, IDX:<N/A>, MET:HEAD, PTH:/, CNT:<N/A>, HDR:{Connection=keep-alive, Content-       Length=0, Host=localhost:9200}
	, HIS:[Allow read access on indice example->[external_authentication->false]] }

[2018-05-07T13:37:42,280][DEBUG][r.suppressed             ] path: /, params: {}                                                                                                                                      
org.elasticsearch.ElasticsearchStatusException: Unauthorized Access                                                                                                                                                  
        at tech.beshu.ror.es.IndexLevelActionFilter$1.onForbidden(IndexLevelActionFilter.java:164) ~[?:?]                                                                                                            
        at tech.beshu.ror.acl.ACL.lambda$check$2(ACL.java:191) ~[?:?]
...

[2018-05-07T13:37:42,285][INFO ][t.b.r.a.ACL          ] FORBIDDEN by default req={ ID:2090974056-422413208#1246, 
	TYP:MainRequest, CGR:N/A, USR:[no basic auth header], BRS:false, KDX:null, ACT:cluster:monitor/main, 
	OA:127.0.0.1, DA:127.0.0.1, IDX:<N/A>, MET:HEAD, PTH:/, CNT:<N/A>, HDR:{Connection=keep-alive, 
	Content-Length=0, Host=localhost:9200}, HIS:[Allow read access on indice example->
	[external_authentication->false]] } 
```
