### ISSUE TITLE
Question: when is the filter called?

### ISSUE THREAD

**Issue by pciccarese** [sscarduzio/elasticsearch-readonlyrest-plugin#35]
I wrote some code to do dynamic indices aliasing. The idea is very simple: I get an index (ex: paolo) and I dynamically check for what indices I have access to and I replace 'paolo' with such list (ex: idx1, idx2). I run this code after the current indices filter is executed and I specify in the configuration that only acceptable index is 'paolo'.

When I tried though, I would get blocked. It turns out the indices filter is called twice. The first time (with index 'paolo') would validate. While the second one (with the indices idx1 and idx2) would fail as it does not meet the 'paolo' requirement. 

Simone, do you know why the filter is called twice?

**Comment by sscarduzio** [comment]
Interesting, no idea. I will try to put some printf and hopefully see what and why this happens.  BTW, thanks Paolo for the features and insights you are contributing to this project!

**Comment by sscarduzio** [comment]
Can't reproduce, mind sharing the conf file?

**Comment by pciccarese** [comment]
Sure (it includes aliases):
```
readonlyrest:
    enable: true
    response_if_req_forbidden: Sorry, your request is forbidden.
    access_control_aliases:

    - in: paolo
      out: [helloworld]

    access_control_rules:

    - name: Accept all requests from localhost
      type: allow
      hosts: [127.0.0.1]
      #indices: [paolo]

    - name: Accept only GETs from other host
      type: allow
      methods: [GET]
      indices: [translational]
```
