### ISSUE TITLE
Running JWT without proxy

### ISSUE THREAD

**Issue by seanziee** [sscarduzio/elasticsearch-readonlyrest-plugin#357]
I'm a bit new with JWT and ROR, but I'm trying to understand how exactly the system would be setup with JWT. 

My goal is to store users and their associated permissions on a JWT server. I'm unclear as to what `roles` are as they aren't explained anywhere. Also can I user `groups` like below? Would a setup like this work?

My goal is to have a JWT pass in:
```
{
   "username" : "user1",
   "kibanaPermission": "basicKibanaAccess", #OR "writeKibanaAccess"
   "DLSfilter": "user1documents"
}
```
and I will have a config like:
```
 access_control_rules:
  - name: Admins
    type: allow
    groups: ["Admin"]
    indices: ["*"]

  - name: Basic Kibana Access
    type: allow
    kibana_access: ro
    indices: [".kibana_@{username}",".kibana_public"]
    groups: ["basicKibanaAccess"]
    jwt_auth:
        name: "jwt_user"
        #roles: ["viewer"]  

   - name: Write Kibana Access
    type: allow
    kibana_access: rw
    indices: [".kibana_@{username}",".kibana_public"]
    groups: ["writeKibanaAccess"]
    jwt_auth:
        name: "jwt_user"
        #roles: ["viewer"]  

 - name: User login
    type: allow
    indices: ["events"]
    filter: "{\"bool\": {\"must\": [{\"term\": {\"user.keyword\": {\"value\": \"@{DLSfilter}\"}}}]}}"
    groups: ["indexFilter"]
    jwt_auth:
        name: "jwt_user"
       # roles: ["viewer"]


   jwt: 
    - name: jwt_user
      signature_algo: RSA
      signature_key: "your_signature"
      user_claim: username
      roles_claim: resource_access.client-app.roles # JSON-path style
      header_name: Authorization
      groups: ["@{kibanaPermission}","indexFilter"]
```

**Comment by sscarduzio** [comment]
Hi @seanziee,
It's not necessary to use groups if you are already using JWT, which comes with the concept of roles. 
I'm under the impression you can achieve what you look for, just with aligning JWT "roles" field in the ACL blocks and using @{user}.

**Comment by seanziee** [comment]
So what are the roles? is `viewer` the only option? And is `resource_access.client-app.roles` implying that you have you JWT come in as
```
{
   "username" : "user1",
   "kibanaPermission": "basicKibanaAccess", #OR "writeKibanaAccess"
   "DLSfilter": "user1documents"
   "resource_access": {
       "client-app": {
          "roles": "viewer"
       }
    }
} 
```

I'm just confused as to how to actually pair users and their associated  permissions using JWT

**Comment by sscarduzio** [comment]
I wrote a better example in the docs:
 https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#json-web-token-jwt-auth

**Comment by seanziee** [comment]
And is my usage of `@{DLSfilter}` correct? I'd like to use DLS for the user as well as defining if they are a `viewer` or `writer`

**Comment by sscarduzio** [comment]
So you can have two ACL blocks one for writers and one for readers, the "filter" rules in these blocks do not need to include the dynamic variables. They are pretty standard off-the manual "filter" rules.

**Comment by seanziee** [comment]
Yeah, but it would be great to be able to have custom filters.

In my ideal use case, I have users sign in and I give them access to kibana as either a reader or writer *as* *well* *as* filtering the index based on some parameter like `username` or some other filter based off the JWT token. My deeper question is can I access the data in the `user_claim` or `roles_claim` and how? And why is there a need to define `roles` under `jwt_auth` as well as a `roles_claim`? Sorry if this is blaringly obvious, I just can't make sense of it. 

```
 - name: User login
    type: allow
    indices: ["events",".kibana"]
    filter: "{\"bool\": {\"must\: [{\"term\": {\"user.keyword\": {\"value\": \"@{username}\"}}}]}}"
    jwt_auth:
        name: "jwt_user"
        roles: ["viewer"]

   jwt: 
    - name: jwt_user
      signature_algo: RSA
      signature_key: "your_signature"
      user_claim: username
      roles_claim: resource_access.client-app.roles # JSON-path style
      header_name: Authorization
```

**Comment by sscarduzio** [comment]
Hi @seanziee, your yaml makes sense, but does not take in consideration the viewer vs writer distinction.

How about this:

```yml
 - name: Access for readers
    indices: ["events", ".kibana"]
    filter: "{\"bool\": {\"must\: [{\"term\": {\"user.keyword\": {\"value\": \"@{username}\"}}}]}}"
    kibana_access: ro
    jwt_auth:
        name: "jwt_user"
        roles: ["viewer"]  # each user will have a role claim either viewer or writer

 - name: Access for writers
    indices: ["events" ,".kibana"]
    filter: "{\"bool\": {\"must\: [{\"term\": {\"user.keyword\": {\"value\": \"@{username}\"}}}]}}"
    kibana_access: rw
    jwt_auth:
        name: "jwt_user"
        roles: ["writer"] # each user will have a role claim either viewer or writer

   jwt: 
    - name: jwt_user
      signature_algo: RSA
      signature_key: "your_signature"
      user_claim: username
      roles_claim: resource_access.client-app.roles # JSON-path style
      header_name: Authorization
```

I don't get this:
> And why is there a need to define roles under jwt_auth as well as a roles_claim?

Anyway of course you can use the values of `user_claim` in the dynamic settings: that would be @{user}. We don't have an equivalent for @{role} because role can potentially be an array. However, if you create one ACL block per role (just viewer and writer in your case) the information will not need to be dynamic. You can hardcode "writer" or "reader" in the filter string if you feel like.

**Comment by seanziee** [comment]
> I don't get this:

>> And why is there a need to define roles under jwt_auth as well as a roles_claim?

I now understand that the `roles` is similar to the `groups` in that it's only purpose is to give the user read or write priv. 

Now I've been testing things a bit, I can't get the @{username} to work. When I manually enter the username in the `filter`, things work correctly but when I use the same username in the `username` part of the token, it doesn't work correctly. Any ideas why?

I also want to add it would be a great feature if we could use other values from the JWT token rather than just the roles and user.

**Comment by tcharlot-datasweet** [comment]
Hi @seanziee 

You need to use `@{user}`. 
Btw, you can check your token with https://jwt.io/

For now, the JWTAuthRule can only set the logged user : 
````java
rc.setLoggedInUser(new LoggedUser(user.get()));
````

**Comment by seanziee** [comment]
@tcharlot-datasweet 
When I use this query `localhost:9200/_search`, I get no results back (I get some back when I manually put in the user which means that it is parsing it as literal `@{user}`)
```
  - name: Publisher Access -- read only 
      indices: ["index"]
      filter: "{\"bool\": {\"must\": [{\"term\": {\"name.keyword\": {\"value\": \"@{user}\"}}}]}}"
      kibana_access: ro
      type: allow
      jwt_auth:
          name: "JWTPublisher"
          roles: ["viewer"] 

```
When I use this query, I get an error:
```
org.elasticsearch.index.query.QueryShardException: Failed to parse query [user.keyword:@{user}]
Caused by: org.apache.lucene.queryparser.classic.ParseException: Cannot parse 'user.keyword:@{user}': Encountered " "}" "} "" at line 1, column 24.
Was expecting:
    "TO" ...
```

```
    - name: Publisher Access -- read only 
      indices: ["index"]
      filter: "{\"bool\": {\"must\": [{\"query_string\": {\"query\": \"name.keyword:@{user}\"}}]}}"
      kibana_access: ro
      type: allow
      jwt_auth:
          name: "JWTPublisher"
          roles: ["viewer"]  
```

Any idea what's going on?

**Comment by seanziee** [comment]
From kibana
```
{"error":{"root_cause":[{"type":"query_shard_exception","reason":"Failed to parse query [name.keyword: @{user} ]"
,"index_uuid":"_vE6Vi1SQ5ekbkZiiiD3sb","index":"index"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"production","node":"btmRxSmaTaGAAnnwtsfMSP","reason":
{"type":"query_shard_exception","reason":"Failed to parse query [name.keyword: @{user}]","index_uuid":"_vE6Vi1SQ5ekbkZiiiD3sb","index":"index","caused_by":
{"type":"parse_exception","reason":"Cannot parse 'name.keyword: @{user}: Encountered \" \"}\" \"} \"\" at line 1, column 30.\nWas expecting:\n    \"TO\" ...\n    ","caused_by":
{"type":"parse_exception","reason":"Encountered \" \"}\" \"} \"\" at line 1, column 30.\nWas expecting:\n    \"TO\" ...\n    "}}}}]},"status":400}
```

**Comment by sscarduzio** [comment]
@seanziee what ROR version are you using?

**Comment by seanziee** [comment]
Awesome, it works now! 

Note that in: `filter: "{\"bool\": {\"must\": [{\"query_string\": {\"query\": \"name.keyword: @{user}\"}}]}}"`, the space between `name.keyword` and `@{user}` is required or it doesn't work. May be worth fixing that or if anyone else stumbles into this, make sure you do that.

@sscarduzio Also, the download on your official page is the `readonlyrest-1.16.19_es6.2.4` version in case you didn't know. Thanks again for all the help... things are working beautifully! :D

Here's my yml file for anyone in the future who wants to dynamically filter their user results from a JWT token!
```

readonlyrest:
    access_control_rules:

    - name: "::KIBANA-SRV::"
      type: allow
      auth_key: kibana:kibana

    - name: User1 Access -- read only 
      indices: ["production",".kibana"]
      # The @{user} is whatever value is stored in "user_claim:" in the JWT section below access control rules. This is a workaround as this current version doesn't allow one to pull in other values from the JWT token other than what you are considering to be the "user". I'm using that to pull in the value I want.Also, the space between field1.keyword: and @{user} is necessary!
      filter: "{\"bool\": {\"must\": [{\"query_string\": {\"query\": \"(field1.keyword: @{user} AND _index:production) OR (_index:.kibana)\"}}]}}"
      kibana_access: ro
      type: allow
      jwt_auth:
          name: "user1"
          roles: ["viewer"]  


    - name: User2 Access -- read only
      indices: ["production",".kibana"]
      # NEED TO CHANGE FILTER TO brandname for production.
      filter: "{\"bool\": {\"must\": [{\"query_string\": {\"query\": \"(field2.keyword: @{user} AND _index:production) OR (_index:.kibana)\"}}]}}"
      kibana_access: ro
      type: allow
      jwt_auth:
          name: "user2"
          roles: ["viewer"]  # each user will have a role claim either viewer or writer

    jwt:
      # Currently, I can't use any variable other than user_claim to distinguish different users. So to differentiate between users, I create a "name" (which acts as the bridge between this section and the ACR section) with a different value for user_claim for each. So only if the token contains that specific user_claim field will it be authorized as that user with a given `user_claim`. user_claim is stored in the @{user} variable.
    - name: user1
      signature_algo: HS256
      signature_key: "your-256-bit-secret"
      user_claim: field1filter
      roles_claim: roles 
      header_name: Authorization

      # Format:
      # {
      #    "field1filter": "fieldsForUser1",
      #    "roles": [
      #      "viewer"
      #    ]
      #  }
      # i.e. eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaWVsZDFmaWx0ZXIiOiJmaWVsZHNGb3JVc2VyMSIsInJvbGVzIjpbInZpZXdlciJdfQ.65CFxGLgrB8-CnSYWhl5luh8RU-ZUSydz4zUR6wV6k0

    - name: user2
      signature_algo: HS256
      signature_key: "your-256-bit-secret"
      user_claim: field2filter
      roles_claim: roles 
      header_name: Authorization

      # Format:
      # {
      #   "field2filter": "fieldsForUser2",
      #   "roles": [
      #     "viewer"
      #   ]
      # }
      # i.e. eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaWVsZDJmaWx0ZXIiOiJmaWVsZHNGb3JVc2VyMiIsInJvbGVzIjpbInZpZXdlciJdfQ.3JddaehDllvJxUZ-I888LiwTUKHxgmI3-SdSiNrre3A
```
