### ISSUE TITLE
ACL order

### ISSUE THREAD

**Issue by itles** [sscarduzio/elasticsearch-readonlyrest-plugin#361]
Hello,
I have two ACL.. If I change order, so WP is first ACL and ADMINS is second ACL, and then I login as admin I get only permission which is specified in WP ACL.

```
    - name: "::ADMINS::"
      kibana_index: ".kibana"
      verbosity: error
      ldap_authentication: "ldap-prod"
      ldap_authorization:
        name: "ldap-prod"
        groups: ["admins"]

    - name: "::WP::"
      kibana_access: rw
      indices: [ "opnsense-*", ".kibana_wp"]
      kibana_index: ".kibana_wp"
      kibana_hide_apps: ["readonlyrest_kbn", "timelion", "monitoring"]
      verbosity: error
      ldap_authentication: "ldap-prod"
      ldap_authorization:
        name: "ldap-prod"
        groups: ["wp"]
```
**How can I use ACL rules regardless of their order?**

I am using:
readonlyrest-1.16.20_pre4_es6.2.3.zip
