### ISSUE TITLE
ES was FORBIDDEN by default

### ISSUE THREAD

**Issue by Howard-Chang** [sscarduzio/elasticsearch-readonlyrest-plugin#372]
Hi, I install readonlyrest plugin, and add a readonlyrest.yml. When I start the es, there are some problems.
p.s. ES:6.2.2 Kibana:6.2.2 ROR:6.2.2
the elasticsearch.yml is default setting, I didn't modify anything.
readonlyrest.yml
```
readonlyrest:
    access_control_rules:

    - name: "::PUBLIC SEARCHBOX::"
      indices: ["public"]
      actions: ["indices:data/read/*"]
```

ES log:
`FORBIDDEN by default req={ ID:1236125300-120540179#9, TYP:MainRequest, CGR:N/A, USR:[no basic auth header], BRS:true, KDX:null, ACT:cluster:monitor/main, OA:127.0.0.1, DA:0:0:0:0:0:0:0:1, IDX:<N/A>, MET:GET, PTH:/, CNT:<N/A>, HDR:{Accept=text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, Accept-Encoding=gzip, deflate, Accept-Language=en-US,en;q=0.5, Cache-Control=max-age=0, Connection=keep-alive, content-length=0, Host=localhost:9200, Upgrade-Insecure-Requests=1, User-Agent=Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0}, HIS:[::PUBLIC SEARCHBOX::->[indices->true, actions->false]] }`
![image](https://user-images.githubusercontent.com/19474557/41856643-32c071ca-78c8-11e8-9a01-2d06398cc826.png)

thank you in advance!

**Comment by sscarduzio** [comment]
Hi @Howard-Chang, 
That's expected. As you can see, the request you sent results in an ES action "cluster:monitor/main", which does not comply to the "indices:data/read/*" you declared in the actions rule.

**Comment by Howard-Chang** [comment]
thank you very much, I got it!
I refer this reference https://forum.readonlyrest.com/t/guide-ror-own-home-and-nginx/227 and follow it step by step. But when I start the kibana there is an error:
```
[root@localhost bin]# sh kibana
  log   [00:45:44.781] [info][status][plugin:kibana@6.2.2] Status changed from uninitialized to green - Ready
  log   [00:45:44.811] [info][status][plugin:elasticsearch@6.2.2] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [00:45:44.905] [info][status][plugin:timelion@6.2.2] Status changed from uninitialized to green - Ready
  log   [00:45:44.994] [info][status][plugin:own_home@6.2.2] Status changed from uninitialized to green - Ready
  log   [00:45:45.001] [info][status][plugin:console@6.2.2] Status changed from uninitialized to green - Ready
  log   [00:45:45.007] [info][status][plugin:metrics@6.2.2] Status changed from uninitialized to green - Ready
  log   [00:45:45.020] [info][plugin:own-home] Proxy server started at http://localhost:19200
  log   [00:45:45.020] [info][listening] Server running at http://localhost:5601
  log   [00:45:45.158] [info][status][plugin:elasticsearch@6.2.2] Status changed from yellow to green - Ready
 error  [00:45:52.796]  TypeError: Cannot read property 'updated_at' of undefined
    at /run/media/es3/80967063-20eb-4c15-82d1-56e01f888254/kibana-6.2.2-linux-x86_64/src/server/saved_objects/client/saved_objects_client.js:442:41
    at next (native)
    at step (/run/media/es3/80967063-20eb-4c15-82d1-56e01f888254/kibana-6.2.2-linux-x86_64/src/server/saved_objects/client/saved_objects_client.js:20:191)
    at /run/media/es3/80967063-20eb-4c15-82d1-56e01f888254/kibana-6.2.2-linux-x86_64/src/server/saved_objects/client/saved_objects_client.js:20:361

```
![image](https://user-images.githubusercontent.com/19474557/41882982-a1ac14bc-791e-11e8-8d72-ecc49f150767.png)

kibana.yml:
```
elasticsearch.username: "kibana"
elasticsearch.password: "kibana"
elasticsearch.url: http://localhost:19200
own_home.session.isSecure: false
own_home.proxy_user_header: x-forwarded-user
own_home.session.secretkey: "mysecretkey-must-be-at-least-32-characters-long"
own_home.local.groups: [ sandbox ]
elasticsearch.requestHeadersWhitelist: [ authorization, x-forwarded-user ]
```

thank you in advance!

**Comment by sscarduzio** [comment]
Hi @Howard-Chang, 
this is an access control list, therefore all the rules you put in a block are in logical AND.
```
      indices: ["*"]
      actions: ["*"] 
```
These two rules up here equates to not having them at all. It's like "I RESTRICT INDICES TO...ALL THE INDICES" means you are not restricting anything, so just remove it.

I'm not sure why data is not appearing, maybe you could see ES logs if they get rejected?

**Comment by Howard-Chang** [comment]
Hi @sscarduzio ok, I got it! 
now the ES can ingest the data,but I face another problem.
I want to filter the data but it seems not successful.
readonlyrest.yml:
```
readonlyrest:
  enable: true
  response_if_req_forbidden: Sorry, your request is forbidden.
  access_control_rules:
  - name: "::USER::"
  proxy_auth: "*"
  indices: ["*"]
  filter: '{\"bool\": { \"should\": [ { \"match\":{\"IPV4_DST_ADDR\":\"192.168.0.0/16\"} }, { \"match\":{\"IPV4_SRC_ADDR\":\"192.168.0.0/16\"} }  ], \"minimum_should_match\": 1 }}'
```
I found Kibana doesn't filter the data. 
original query:
```
"query": {
    "bool": {
      "should": [
        {
            "match":{"IPV4_DST_ADDR":"192.168.0.0/16"}
        },
        {
            "match":{"IPV4_SRC_ADDR":"192.168.0.0/16"}
        }
      ],
      "minimum_should_match": 1
    }
}
```

**Comment by sscarduzio** [comment]
You have a YAML indentation problem. The proxy_auth, indices and filter rules should align with the 'n' of name.

**Comment by Howard-Chang** [comment]
ok, I modified the readonlyrest.yml:
```
readonlyrest:
  enable: true
  response_if_req_forbidden: Sorry, your request is forbidden.
  access_control_rules:
  - name: "::USER::"
    type: allow
    indices: ["*"]
    groups: ["nginx"]
    filter: '{\"bool\": { \"should\": [ { \"match\":{\"IPV4_DST_ADDR\":\"192.168.0.0/16\"} }, { \"match\":{\"IPV4_SRC_ADDR\":\"192.168.0.0/16\"} }  ], \"minimum_should_match\": 1 }}'
  - name: Basic Kibana Access
    type: allow
    kibana_access: ro
    indices: ["*"]
    groups: ["nginx"]
elasticsearch log:

`[2018-06-27T15:58:45,656][INFO ][t.b.r.a.ACL              ] FORBIDDEN by default req={ ID:333117069-1340905389#137, TYP:NodesInfoRequest, CGR:N/A, USR:[no basic auth header], BRS:false, KDX:null, ACT:cluster:monitor/nodes/info, OA:163.19.163.239, DA:163.19.163.239, IDX:<N/A>, MET:GET, PTH:/_nodes?filter_path=nodes.*.version%2Cnodes.*.http.publish_address%2Cnodes.*.ip, CNT:<N/A>, HDR:{connection=keep-alive, content-length=0, host=localhost:19200, x-forwarded-for=127.0.0.1, x-forwarded-port=33680, x-forwarded-proto=http}, HIS:[::USER::->[groups->false]], [Basic Kibana Access->[groups->false]] }`

thank you !

**Comment by Howard-Chang** [comment]
ok, I got it! I modified readonlyrest.yml, but there are some problems:

```
readonlyrest:
  enable: true
  response_if_req_forbidden: Sorry, your request is forbidden.
  access_control_rules:
  - name: "::USER::"
    type: allow
    indices: ["*"]
    actions: ["*"]
    filter: "{\"bool\": { \"should\": [ { \"match\":{\"IPV4_DST_ADDR\":\"192.168.0.0/16\"} }, { \"match\":{\"IPV4_SRC_ADDR\":\"192.168.0.0/16\"} }  ], \"minimum_should_match\": 1 }}"
```
when I press the button in kibana, and it occurs the error.
kibana log:
```
Unhandled rejection [undefined] Sorry, your request is forbidden. :: {"path":"/.kibana_nginx/doc/config%3A6.2.2/_create","query":{},"body":"{\"type\":\"config\",\"config\":{\"buildNum\":16588}}","statusCode":403,"response":"{\"error\":{\"root_cause\":[{\"reason\":\"Sorry, your request is forbidden.\"}],\"reason\":\"Sorry, your request is forbidden.\"},\"status\":403}"}
    at respond (/home/wlogger/Downloads/kibana-6.2.2-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:295:15)
    at checkRespForFailure (/home/wlogger/Downloads/kibana-6.2.2-linux-x86_64/node_modules/elasticsearch/src/lib/transport.js:254:7)
    at HttpConnector.<anonymous> (/home/wlogger/Downloads/kibana-6.2.2-linux-x86_64/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
    at IncomingMessage.bound (/home/wlogger/Downloads/kibana-6.2.2-linux-x86_64/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```
ES log:
```
[2018-06-27T16:15:53,764][INFO ][t.b.r.a.ACL              ] ALLOWED by { name: '::USER::', policy: ALLOW} req={ ID:357406810-1730359545#175, TYP:SearchRequest, CGR:N/A, USR:[no basic auth header], BRS:false, KDX:null, ACT:indices:data/read/search, OA:163.19.163.239, DA:163.19.163.239, IDX:.kibana_nginx, MET:POST, PTH:/.kibana_nginx/_search?size=10000&from=0&_source=index-pattern.title%2Ctype%2Ctitle, CNT:<OMITTED, LENGTH=80>, HDR:{connection=keep-alive, Content-Length=80, content-type=application/json, cookie=sid=Fe26.2**6a390ba985e48413887de0e3d8b2fa26f92be5d0c2ec8483adc01a5919c1db9d*CRA5r5EB7uC7I_Dyy-rPoQ*3VL9rByAuMw6FyItJEJ1JWU4QKmdVZwA4wkZOK21s6tRwtI2fy26VJRxo1PE1VrwVRgzBlHIbW1TPeRCA1_Et_4awNrHq0sG9ck6JGaXjW7MfHm0RFb8O3GYVVWmcPglYUDeE3qOv3e_TQ4B3KHBbg**89050ae700a985da3fd9eec68b3684e6c99755d837812b0ae4354696b8ccc3db*ACEHHY8PDhsXFaFsLkG_jMwTtIKeHpvC-DnEYchePPA; own-home-session=Fe26.2**c2e1a85423c21f181a3ac3f2e605fe4abc43e33add72502a40c0defab087a051*cHQmUCq_yXd-vvnLuQaU7w*O_Fb-IEVCCNRN9bos3mmWIEU8yNXQ86thY13jgVikAu5PuW0kP5Vb1Opc_G2x_V43ry3UThEpDZojvzhrIldLGo1gw_fXDbdSraS6kWiRiSoSslmM2ZH7-HJEABFPA7v**a843bf24eb9cf17569ccdff6bf499b06986e80f6a02ad014271f591528d95e27*znnUzFburLdXvktalHr2AEkyqXkWfR9ya5I9TMDg6JI, host=localhost:19200, x-forwarded-for=127.0.0.1, x-forwarded-port=36882, x-forwarded-proto=http, x-proxy-user=nginx}, HIS:[::USER::->[filter->true, indices->true, actions->true]] }
//    when I when I press the button in kibana, error occurs.
[2018-06-27T16:15:53,810][INFO ][t.b.r.a.ACL              ] FORBIDDEN by default req={ ID:183867872-171551963#179, TYP:IndexRequest, CGR:N/A, USR:[no basic auth header], BRS:false, KDX:null, ACT:indices:data/write/index, OA:163.19.163.239, DA:163.19.163.239, IDX:.kibana_nginx, MET:POST, PTH:/.kibana_nginx/doc/config%3A6.2.2/_create, CNT:<OMITTED, LENGTH=45>, HDR:{Connection=keep-alive, Content-Length=45, content-type=application/json, Host=163.19.163.239:9200}, HIS:[::USER::->[filter->false, indices->true, actions->true]] }
```

**Comment by sscarduzio** [comment]
Please see the ROR documentation page  for examples on how to set basic auth credentials in kibana.yml.

```
 USR:[no basic auth header]  <--- this means kibana is not setting basic auth credentials 
```


Are these back? :-)
```
    indices: ["*"]
    actions: ["*"]
```

Also please note that filter and fields rules need to live in their own block if you need to use them in with a read/write session in Kibana.  This is because they will return "NO_MATCH" for any non-RO request.

**Comment by sscarduzio** [comment]
I have never used own home, it's quite complicated as a solution. Involves two level of proxies and AFAIK does not even provide a logout button.

Anyways, you need to break down this:

```yml
  - name: User1 login
    type: allow
    indices: ["logstash-*"]
    groups: ["user1group"]
    filter: "{\"bool\": { \"should\": [ { \"match\":{\"IPV4_DST_ADDR\":\"192.168.0.0/16\"} }, { \"match\":{\"IPV4_SRC_ADDR\":\"192.168.0.0/16\"} }  ], \"minimum_should_match\": 1 }}"
```

Into this
```yml
  - name: "User1 login intercept reads and filter"
    groups: ["user1group"]
    filter: "{\"bool\": { \"should\": [ { \"match\":{\"IPV4_DST_ADDR\":\"192.168.0.0/16\"} }, { \"match\":{\"IPV4_SRC_ADDR\":\"192.168.0.0/16\"} }  ], \"minimum_should_match\": 1 }}"

  - name: User1 login (all the rest)
    type: allow
    indices: ["logstash-*"]


 
```

**Comment by Howard-Chang** [comment]
I modified readonlyrest.yml as you said:
```
readonlyrest:
  enable: true
  response_if_req_forbidden: Sorry, your request is forbidden.
  access_control_rules:

  - name: Basic Kibana Access
    type: allow
    kibana_access: ro
    indices: [".kibana_@{X-Forwarded-User}",".kibana_public"]
    groups: ["basicKibanaAccess"]

  - name: "User1 login intercept reads and filter"
    groups: ["user1group"]
    filter: "{\"bool\": { \"should\": [ { \"match\":{\"IPV4_DST_ADDR\":\"192.168.0.0/16\"} }, { \"match\":{\"IPV4_SRC_ADDR\":\"192.168.0.0/16\"} }  ], \"minimum_should_match\": 1 }}"

  - name: User1 login (all the rest)
    type: allow
    indices: ["logstash-*"]

  - name: "::KIBANA-SRV::"
    type: allow
    auth_key: kibana:kibana

  users:
  - username: nginx
    proxy_auth: "nginx"
    groups: ["user1group","basicKibanaAccess"]
```
the kibana can work now, but there's no match data.
![image](https://user-images.githubusercontent.com/19474557/42006991-d54c9552-7aaf-11e8-801c-96e7bf88a1ab.png)
when I delete the filter query string the data is complete and correct.
I think there are some problems in the filter : (
