### ISSUE TITLE
plugin with active directory

### ISSUE THREAD

**Issue by eyhanna** [sscarduzio/elasticsearch-readonlyrest-plugin#376]
i have configured the plugin with active directory,everything works fine  but for a while. each day i have to restart the plugin because after a while he start giving giving FORBIDDEN by default, like it stopes checking with active directory.  

my config is the following:

```yml
 http.cors.allow-origin: /https?:\/\/localhost(:[0-9]+)?/
#http.cors.allow-origin: "*"

http.cors.enabled: true
http.cors.allow-headers: Authorization
readonlyrest:
  enable: true
#  audit_collector: true
#  prompt_for_basic_auth: false

  access_control_rules:

    -
      name: "workaround"
      actions: [ "indices:data/read/field_caps*" ]

    -
      name: account used by kibana
      type: allow
      auth_key: kibana:kibana

    -
      name: "::test::"
      type: allow
      auth_key_sha256: "67bca4efc1f7640a030456ca0e1be8e65c18f0ef1b14839c804a39e0ea35de11"
    -
      name: "::bulzak::"
      auth_key_sha256: "16b1ffaa7d087cac0caee375398dec003bbc74bd4be6bfb0c5af6da31d448808"
      type: allow

    -
      name: allow Admin
      type: allow
      ldap_auth:
        name: "ldap2"
        groups: ["elk-administrators"]
      indices: [".kibana","*"]

    -
      name: allow admin to kibana
      type: allow
      ldap_auth:
        name: "ldap2"
        groups: ["elk-developers"]
      indices: [".kibana","*"]
      kibana_access: rw


    -
      name: give full access to service account
      type: allow
      ldap_auth:
        name: "ldap3"
        groups: ["elk-ReadWrite"]
      indices: [".kibana","*"]

    -
      name: read-only to kibana
      type: allow
      ldap_auth:
        name: "ldap2"
        groups: ["elk-developers"]
      indices: [".kibana","*"]
      kibana_access: ro_strict


    - name: "::LOGSTASH::"
      auth_key_sha256: "c57a32438a4840e993fe2d73b1c03c2b51ff9ba91b6395c0a6c4755da553fdac"
      type: allow
      actions: ["cluster:monitor/main","indices:admin/types/exists","indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create"]
      indices: ["logstash-*", "iislog-*","*"]

    - name: curator
      auth_key_sha256: "963fcc405f78f29f81168ea80058f6e40be0b1d15f4ceb3ddbd0c0561cc6bbb1"
      type: allow

    - name : cerebro
      auth_key_sha256: "76f4e83ae5fea152eb214be15fb493dc2f81f8e3a6ab67aeccf3b8b22dd66bce"
      type: allow
      indices: ["<no-index>", ".kibana", "*"]


  ldaps:

    -
      search_user_base_DN: 'ou=permanent,ou=RC_Users,dc=mycluster,dc=lab'
      port: 389
      verbosity: "info"
      search_groups_base_DN: 'ou=permanent,ou=RC_Users,dc=mycluster,dc=lab'
      host: 100wsproddc012.mycluster.lab
      name: ldap2
      unique_member_attribute: Member
      connection_pool_size: 30                                  # optional, default 30
      connection_timeout_in_sec: 30                             # optional, default 1
      request_timeout_in_sec: 30                                # optional, default 1
      cache_ttl_in_sec: 60
      ssl_trust_all_certs: true
      ssl_enabled: false
      user_id_attribute: "sAMAccountName"
      bind_dn: 'cn=0svc_identityelastic,ou=service,ou=RC_Users,dc=mycluster,dc=lab'
      bind_password: Passw0rd

    -
      search_user_base_DN: 'ou=service,ou=RC_Users,dc=mycluster,dc=lab'
      port: 389
      verbosity: "info"
      search_groups_base_DN: 'ou=permanent,ou=RC_Users,dc=mycluster,dc=lab'
      host: 100wsproddc012.mycluster.ca
      name: ldap3
      unique_member_attribute: Member
      connection_pool_size: 30                                  # optional, default 30
      connection_timeout_in_sec: 30                             # optional, default 1
      request_timeout_in_sec: 30                                # optional, default 1
      cache_ttl_in_sec: 60
      ssl_trust_all_certs: true
      ssl_enabled: false
      user_id_attribute: "sAMAccountName"
      bind_dn: 'cn=0svc_identityelastic,ou=service,ou=RC_Users,dc=mycluster,dc=lab'
      bind_password: Passw0rd


```
