### ISSUE TITLE
Kibana_access seems not work. 

### ISSUE THREAD

**Issue by Howard-Chang** [sscarduzio/elasticsearch-readonlyrest-plugin#379]
Hi, I want to forbid users to modified the template Dashboard, Visualization and can only modified their own Dashboard or Visualization. 
The  kibana_access: ro_strict seems not work.
Below is my readonlyrest.yml.
```
readonlyrest:
  enable: true
  response_if_req_forbidden: Sorry, your request is forbidden.
  access_control_rules:

  - name: Basic Kibana Access
    type: allow
    kibana_access: ro
    indices: [".kibana_@{X-Forwarded-User}"]
    groups: ["basicKibanaAccess"]

  - name: template filter
    type: allow
    kibana_access: ro_strict
    indices: [".kibana_template"]
    groups: ["template_filter"]

  - name: admin
    type: allow
    groups: ["admin"]
    indices: ["*"]

  - name: "nginx login intercept reads and filter"
    groups: ["user1group"]
    filter: "{\"bool\": { \"should\": [ { \"match\":{\"IPV4_DST_ADDR\":\"192.168.0.0/16\"} }, { \"match\":{\"IPV4_SRC_ADDR\":\"192.168.0.0/16\"} }  ], \"minimum_should_match\": 1 }}"

  - name: "aaa login intercept reads and filter"
    groups: ["user2group"]

  - name: "howard login intercept reads and filter"
    groups: ["user3group"]
    filter: "{\"bool\": { \"should\": [ { \"match\":{\"IPV4_DST_ADDR\":\"163.19.0.0/16\"} }, { \"match\":{\"IPV4_SRC_ADDR\":\"163.19.0.0/16\"} }  ], \"minimum_should_match\": 1 }}"

  - name: "school1 login intercept reads and filter"
    groups: ["user4group"]
    filter: "{\"bool\": { \"should\": [ { \"match\":{\"IPV4_DST_ADDR\":\"120.104.192.0/18\"} }, { \"match\":{\"IPV4_SRC_ADDR\":\"120.104.192.0/18\"} }  ], \"minimum_should_match\": 1 }}"

  - name: "school2 login intercept reads and filter"
    groups: ["user5group"]
    filter: "{\"bool\": { \"should\": [ { \"match\":{\"IPV4_DST_ADDR\":\"203.72.251.0/24\"} }, { \"match\":{\"IPV4_SRC_ADDR\":\"203.72.251.0/24\"} }  ], \"minimum_should_match\": 1 }}"

  - name: "gg login intercept reads and filter"
    groups: ["user6group"]
 filter: "{\"bool\": { \"should\": [ { \"match\":{\"IPV4_DST_ADDR\":\"203.72.252.0/24\"} }, { \"match\":{\"IPV4_SRC_ADDR\":\"203.72.252.0/24\"} }  ], \"minimum_should_match\": 1 }}"

  - name: User1 login (all the rest)
    type: allow
    indices: ["logstash-*","*"]

  - name: "::KIBANA-SRV::"
    type: allow
    auth_key: kibana:kibana

  users:
  - username: admin
    proxy_auth: "admin"
    groups: ["admin","basicKibanaAccess","template_filter"]
  - username: nginx
    proxy_auth: "nginx"
    groups: ["user1group","basicKibanaAccess","template_filter"]
  - username: aaa
    proxy_auth: "aaa"
    groups: ["user2group","basicKibanaAccess","template_filter"]
  - username: howard
    proxy_auth: "howard"
    groups: ["user3group","basicKibanaAccess","template_filter"]
  - username: school1
    proxy_auth: "school1"
    groups: ["user4group","basicKibanaAccess","template_filter"]
  - username: school2
    proxy_auth: "school2"
    groups: ["user5group","basicKibanaAccess","template_filter"]
  - username: gg
    proxy_auth: "gg"
    groups: ["user6group","basicKibanaAccess","template_filter"]

thank you in advance !
```
