### ISSUE TITLE
Dev tool can't work.

### ISSUE THREAD

**Issue by Howard-Chang** [sscarduzio/elasticsearch-readonlyrest-plugin#381]
Hi, below is my readonlyrest.yml. I have a problem that when the user login, and use the Dev tool to query. Every time even it matches documents the return data is 0.
I am sure there are some documents matches, but Dev tool didn't return everything.
![image](https://user-images.githubusercontent.com/19474557/42927264-7ec34f06-8b66-11e8-9685-14ab498c685c.png)
![image](https://user-images.githubusercontent.com/19474557/42927446-2584e368-8b67-11e8-9ea4-087ac268ffbc.png)
 ```
readonlyrest:
  enable: true
  response_if_req_forbidden: Sorry, your request is forbidden.
  access_control_rules:

 - name: Basic Kibana Access
    type: allow
    kibana_access: ro
    indices: [".kibana_@{X-Forwarded-User}"]
    groups: ["basicKibanaAccess"]
    actions: ["*"]

  - name: template filter
    type: allow
    kibana_access: ro_strict
    indices: [".kibana_template"]
    groups: ["template_filter"]

  - name: "Alex login intercept reads and filter"
    groups: ["user1group"]
    filter: "{\"bool\": { \"should\": [ { \"match\":{\"IPV4_DST_ADDR\":\"192.168.0.0/16\"} }, { \"match\":{\"IPV4_SRC_ADDR\":\"192.168.0.0/16\"} }  ], \"minimum_should_match\": 1 }}"

  - name: "test1 login intercept reads and filter"
    groups: ["user2group"]
  - name: "howard login intercept reads and filter"
    groups: ["user3group"]
    filter: "{\"bool\": { \"should\": [ { \"match\":{\"IPV4_DST_ADDR\":\"163.19.0.0/16\"} }, { \"match\":{\"IPV4_SRC_ADDR\":\"163.19.0.0/16\"} }  ], \"minimum_should_match\": 1 }}"

  - name: User1 login (all the rest)
    type: allow
    indices: ["logstash-*",".kibana_@{X-Forwarded-User}"]

  - name: "::KIBANA-SRV::"
    type: allow
    auth_key: kibana:kibana

  users:
  - username: alex
    proxy_auth: "alex"
    groups: ["user1group","basicKibanaAccess","template_filter"]
  - username: test1
    proxy_auth: "test1"
    groups: ["user2group","basicKibanaAccess","template_filter"]

```
thank you in advance!
