### ISSUE TITLE
potential bug on kibana_index/kibana_access feature

### ISSUE THREAD

**Issue by fbaligand** [sscarduzio/elasticsearch-readonlyrest-plugin#383]
Given I define this rule : 
```
    - name: "business users - kibana"
      proxy_auth: "*"
      ldap_authorization:
        name: "ldap_ad"
        groups: ["MY_BUSINESS_GROUP"]
      kibana_index: ".kibana.myapp"
      kibana_access: ro
```

User can access any other index :
```
[2018-07-31T14:32:22,392][INFO ][tech.beshu.ror.acl.ACL   ] ALLOWED by { name: 'business users - kibana', policy: ALLOW} req={ ID:772189945-1430116073#6728, TYP:SearchRequest, CGR:N/A, USR:businessuser1, BRS:true, KDX:.kibana.myapp, ACT:indices:data/read/search, OA:127.0.0.1, DA:127.0.0.1, IDX:index1, MET:GET, PTH:/index1/_search?size=0&pretty, CNT:<N/A>, HDR:{Accept=*/*, content-length=0, Host=localhost:10400, User-Agent=curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.27.1 zlib/1.2.3 libidn/1.18 libssh2/1.4.2, x-forwarded-user=businessuser1}, HIS:[business users - kibana->[ldap_authorization->true, kibana_access->true, proxy_auth->true, kibana_index->true]] }
```

So that it works as expected, I have to add the following option : 
```
      indices: [".kibana.myapp"]
```

=> Is this a bug/regression ?

Reproduced on : 
- Elasticsearch 6.1.3 with ROR 1.16.18
- Elasticsearch 6.3.2 with ROR 1.16.23

**Comment by sscarduzio** [comment]
Hi @fbaligand,

The kibana_index rule does not do anything for preventing any access to any index, it just passes on this information to kibana_access rule so it can allow some write/update/delete operations that are typical of a kibana session while protecting any other index from data deletion or change.

If you want to disallow said user(s) from reading arbitrary indices, you need to use the indices rule exactly like you are doing.

In a realistic scenario though, a Kibana session that does access any index is very weird, not very useful at least. Therefore,  I would add some other data index to that indices rule, so the dashboard actually show some data.

**Comment by fbaligand** [comment]
Well, aside this "kibana" rule, I have already a "data" rule to define read-only access to precise business indices (not all) : 
```
    - name: "business users - data"
      proxy_auth: "*"
      ldap_authorization:
        name: "ldap_ad"
        groups: ["MY_BUSINESS_GROUP"]
      indices: ["myapp-*"]
      actions: ["indices:data/read/*"]
```

Despite this rule, if I have another index (say 'index1'),  my business users have access to "index1", that is not desired.

**Comment by sscarduzio** [comment]
Yes that is how ROR works: if have a block where all rules match (i.e. authentication, kibana_access), and you don't add the indices rule, then that block will be matched and no further blocks are going to be evaluated. 

Am I missing something?

**Comment by fbaligand** [comment]
So it means that when I define a `kibana_access` rule, I must define both `kibana_index` and `indices` ?
Like this : 
```
- name: "business users - kibana"
      kibana_index: ".kibana.myapp"
      kibana_access: ro
      indices: [".kibana.myapp"]
```

If I understand well, `kibana_access: ro` rule means "read+some writes access to .kibana index AND read-only access to all other indices". Right ?

**Comment by fbaligand** [comment]
And so, if I still understand well, my 2 existing rules can be merged into : 
```
    - name: "business users"
      proxy_auth: "*"
      ldap_authorization:
        name: "ldap_ad"
        groups: ["MY_BUSINESS_GROUP"]
      kibana_index: ".kibana.myapp"
      kibana_access: ro
      indices: [".kibana.myapp", "myapp-*"]
```

=> It would be equivalent ?
