### ISSUE TITLE
kibana_access: ro => short urls can not be created

### ISSUE THREAD

**Issue by fbaligand** [sscarduzio/elasticsearch-readonlyrest-plugin#384]
Documentation says "kibana_access: ro" lets to create short urls : 
https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#kibana_access-rule

But when I try to create a short url using Kibana, I get this kibana error : 
`Url Shortener: Error 403 Forbidden: forbidden: [undefined] forbidden`

In the readonlyrest server logs, I have this forbidden audit log : 
`[2018-08-02T12:13:25,649][INFO ][tech.beshu.ror.acl.ACL   ] FORBIDDEN by default req={ ID:1273653959-890255527#1350, TYP:IndexRequest, CGR:N/A, USR:user1, BRS:false, KDX:.kibana, ACT:indices:data/write/index, OA:127.0.0.1, DA:127.0.0.1, IDX:.kibana, MET:POST, PTH:/.kibana/doc/url%3A1c002fc03796438321982a1a64158bd5/_create?refresh=wait_for, CNT:<OMITTED, LENGTH=394>, HDR:{Connection=keep-alive, Content-Length=394, content-type=application/json, Host=localhost:10400, x-forwarded-user=user1}, HIS:[kibana standard->[kibana_access->false, proxy_auth->true]] }
`

And here's my readonlyrest yaml config : 
```
readonlyrest:
    enable: true
    access_control_rules:
    - name: "kibana standard"
      proxy_auth: "*"
      ldap_authorization:
        name: "ldap_ad" 
        groups: ["BUSINESS_USERS"]
      kibana_index: ".kibana"
      kibana_access: ro
```

Elasticsearch/Kibana version : 6.3.2
ROR version : 1.16.23

=> Is it a bug or I misunderstood documentation ?
