### ISSUE TITLE
DLS Filter applied to .kibana index 

### ISSUE THREAD

**Issue by francarl** [sscarduzio/elasticsearch-readonlyrest-plugin#385]
Please, take a look at this plugin configuration:

```
readonlyrest:

    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin

    access_control_rules:

    - name: "::LOGSTASH::"
      auth_key: logstash:logstash
      actions: ["cluster:monitor/main","indices:admin/types/exists","indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create"]
      indices: ["logstash-*"]
      verbosity: error  

    - name: "::USER::"
      proxy_auth:
        proxy_auth_config: "user1"
        users: ["*"]
      kibana_access: ro
      indices: [".kibana", ".kibana-devnull", "logstash-*"]
      filter: '{"query_string":{"query": "appname: @{X-Auth-App} "}}' 

    - name: "::KIBANA-SRV::"
      auth_key: kibana:kibana
      verbosity: error      
      
      
    proxy_auth_configs:
    - name: "user1"
      user_id_header: "X-Auth-Username"                            
      
```

Queries towards logstash-* indexes are filtered by values read from http header X-Auth-App provided by external authentication (keycloak in this case).
But Kibana isn't working well because the DLS Filter is applied also to .kibana index. 
I think that should be better to outline which indexes  DLS Filter should be applied to. 
Do you agree?
Thanks
Francesco
