### ISSUE TITLE
[req] Support for regular-expression matching on headers

### ISSUE THREAD

**Issue by dekimsey** [sscarduzio/elasticsearch-readonlyrest-plugin#389]
It'd be wonderful to be able to perform tests against the contents of headers and not need to be a full matching entry.

Our OAuth2 proxy is adding roles like such, `x-forwarded-roles: foo|bar|baz`. Right now it is not possible to configure the headers to search for the `bar` token in the given header. It is a full-string match.

Possible example of usage:
```
# Given a admin's header: `x-forwarded-roles: admin|user`
# Or a user's header: `x-forwarded-roles: user`

access_control_rules:
  - name: "Admin"
    type: allow
    headers:
      - "x-forwarded-roles~(^|\|)admin($|\|)"
    kibana_access: rw

  - name: "Admin"
    type: allow
    headers:
      - "x-forwarded-roles~(^|\|)user($|\|)"
    kibana_access: ro

  - name: "Unauthenticated"
    type: forbid
```

Thanks!
