### ISSUE TITLE
JWT signature_algo: NONE gives error "unrecognised algorithm family NONE. Should be either of: HMAC, EC, RSA"

### ISSUE THREAD

**Issue by plhosk** [sscarduzio/elasticsearch-readonlyrest-plugin#396]
I'm trying to use unsigned JWT tokens and this is the error I'm getting. 

```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "runtime_exception",
        "reason" : "unrecognised algorithm family NONE. Should be either of: HMAC, EC, RSA"
      }
    ],
    "type" : "runtime_exception",
    "reason" : "unrecognised algorithm family NONE. Should be either of: HMAC, EC, RSA"
  },
  "status" : 500
}
```
readonlyrest.yml
```
readonlyrest:
  access_control_rules:
    - name: Valid JWT token with a viewer role
      indices: ["editlog1"]
      jwt_auth:
        name: "jwt_provider_1"
        roles: ["viewer"]
  jwt:
    - name: jwt_provider_1
      header_name: Authorization
      roles_claim: roles
      signature_algo: None
      signature_key: "testtesttesttesttesttesttesttest"
      user_claim: email
```

readonlyrest Version: v1.16.30_es6.5.0
