### ISSUE TITLE
proxy_auth not working

### ISSUE THREAD

**Issue by parosio** [sscarduzio/elasticsearch-readonlyrest-plugin#405]
Hello,
we're in the middle of a migration from EL 5.4.0 with ROR 1.16.17 to EL 6.5.1 with ROR 1.16.32 (on a brand new server).

Added the xpack security exclusion line to elasticsearch.yml (and to kibana.yml):
`xpack.security.enabled: false`
Moved RoR configuration to a separate file readonlyrest.yml.

Our current configuration has either auth_key entries (for application users) and proxy_auth entries (for actual users), with access to specific indices.
UserIDs are forwarded by an ngnx reverse proxy in X-Forwarded-User header (added in kibana.yml the line:
`elasticsearch.requestHeadersWhitelist: [ 'x-forwarded-user' ])`.

The problem we experience is the following: the users with the proxy-auth are FORBIDDEN by RoR.

Our config:

```
# ---------------------------------- readonlyrest -----------------------------------
readonlyrest:
    enable: true
    ssl:
      enable: true
      keystore_file: "path_2_keystore/keystore_elk_st.jks"
      keystore_pass: ********
      key_pass: ********

    response_if_req_forbidden: Forbidden by ELASTIC

    access_control_rules:

    - name: "::KIBANA-SRV::"
      auth_key: kibana:pwd_kib
      verbosity: error
      type: allow

    - name: "::NAGIOS::"
      auth_key: nagios:pwd_nag
      type: allow
      verbosity: error
      actions: ["cluster:monitor/main", "cluster:monitor/health", "cluster:monitor/state", "cluster:monitor/stats", "cluster:monitor/nodes/info", "cluster:monitor/nodes/stats"]


    #
    # Groups definition for real users
    #
    - name: "HQ Admins"
      type: allow
      # verbosity: error
      kibana_access: rw
      groups: ["HQ_Admin"]
      indices: [ "all-*", "logstash-*", ".kibana", ".kibana-devnull" ]

    users:

    - username: "adminUsers"
      proxy_auth: ["PAROSIO", "TRISAF"]
      groups: ["HQ_Admin"]
```

With a simple interrogation using **nagios** user everything works:

```
user@as1-st:~> curl -vvv  "http://localhost:9202/_cat/indices" -u nagios:pwd_nag
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9202 (#0)
* Server auth using Basic with user 'nagios'
> GET /_cat/indices HTTP/1.1
> Authorization: Basic bmFnaW9zOnB3ZF9uYWc=
> User-Agent: curl/7.37.0
> Host: localhost:9202
> Accept: */*
> 
< HTTP/1.1 200 OK
< x-ror-username: nagios
< content-type: text/plain; charset=UTF-8
< content-length: 27260
< 
yellow open all-vuln-ass-score-eastafrica               bCLBdYY6Rr6z3QMavtaKKA 1 2        8     0   15.3kb   15.3kb
yellow open all-vuln-ass-all-china                      bkHgiR1VSdy9AJy_pxcs3A 1 2     2613  1742  648.7kb  648.7kb
yellow open errors-av-threats                           aLUB68_VQo-xd-oIuGyHoQ 5 1       25    27  698.2kb  698.2kb
```

With mine (I should have access to everything, and the interrogation works on current (5.4) environment), I get stopped by ROR:
```
curl -vvv  "http://localhost:9202/_cat/indices?pretty" -H 'X-Forwarded-User:PAROSIO'
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9202 (#0)
> GET /_cat/indices?pretty HTTP/1.1
> User-Agent: curl/7.37.0
> Host: localhost:9202
> Accept: */*
> X-Forwarded-User:PAROSIO
> 
< HTTP/1.1 401 Unauthorized
< WWW-Authenticate: Basic
< content-type: application/json; charset=UTF-8
< content-length: 166
< 
{
  "error" : {
    "root_cause" : [
      {
        "reason" : "Forbidden by Infosync"
      }
    ],
    "reason" : "Forbidden by ELASTIC"
  },
  "status" : 401
}
* Connection #0 to host localhost left intact
```
and the Elastic log shows:

```
[2019-01-09T11:44:36,579][INFO ][t.b.r.a.ACL              ] [mCMhoMa] FORBIDDEN by default req={ ID:1117882189-347687854#2562, TYP:ClusterStateRequest, CGR:N/A, USR:PAROSIO, BRS:true, KDX:null, ACT:cluster:monitor/state, OA:127.0.0.1, DA:127.0.0.1, IDX:, MET:GET, PTH:/_cat/indices?pretty, CNT:<N/A>, HDR:{User-Agent=curl/7.37.0, content-length=0, Host=localhost:9202, Accept=*/*, X-Forwarded-User=PAROSIO}, HIS:[::LOGSTASH::->[auth_key->false]], [::KIBANA-SRV::->[auth_key->false]], [::PHP::->[auth_key->false]], [::NAGIOS::->[auth_key->false]], [HQ Admins->[groups->false]] } 
```
as if my UserID hadn't been linked to the "HQ Admins" group.

As I said before, the configuration of the not-working environment (6.5.1) is the same as the working one (5.4).
Any advice would be highly appreciated!

**Comment by sscarduzio** [comment]
hi @parosio,

Interesting way to use the "users" section. The local users declaration relies on the fact that "username" is the actual user name.  So I don't think it *should* have worked to begin with. What I would do is the following instead:

```yml
users:
    - username: "PAROSIO"
       proxy_auth: ["PAROSIO"]
       groups: ["HQ_Admin"]

    - username: "TRISAF"
       proxy_auth: ["TRISAF"]
       groups: ["HQ_Admin"]

```

**Comment by parosio** [comment]
hi @sscarduzio, 
actually we relied heavily on the former syntax: 
our **usernames** were simple labels, and actual UIDs were contained in the **proxy_auth** list:
```
    - name: eastafrica
      kibana_access: ro
      groups: ["eastafrica"]
      indices: ["*eastafrica*", ".kibana", ".kibana-devnull"]
     .   .   . 
    - username: eastafrica_users
      proxy_auth: ["EA_123456", "EA_987654"]
      groups: ["eastafrica"]
```

By adhering to your example, would it be possible to associate multiple groups to a single user?
In our current version the last "username" section would override previous ones.

I'm going to test your solution and let you know asap.

**Comment by sscarduzio** [comment]
Well then why do you use local groups at all?

```yml
    - name: "HQ Admins"
      type: allow
      # verbosity: error
      kibana_access: rw
      proxy_auth: ["PAROSIO", "TRISAF"]
      indices: [ "all-*", "logstash-*", ".kibana", ".kibana-devnull" ]

    - name: eastafrica
      kibana_access: ro
      proxy_auth: ["EA_123456", "EA_987654"] # or even:  proxy_auth: ["EA_*"]
      indices: ["*eastafrica*", ".kibana", ".kibana-devnull"]
```

**Comment by parosio** [comment]
I think we followed some example, and, as a matter of principle, to decouple ACLs and Users.

Going to test this. Thanks

**Comment by parosio** [comment]
Hi @sscarduzio , 
I've tested the following and it works for me and @trisaf , as well as for **VIET** and **CONGO** users / acls.

```
    access_control_rules:
    .    .    .
    - name: "HQ Admins"
      type: allow
      kibana_access: rw
      proxy_auth: ["PAROSIO", "TRISAF" ]
     # groups: ["HQ_Admin"]
      indices: [ "all-*", "logstash-*", ".kibana", ".kibana-devnull" ]

    - name: "vietnam"
      type: allow
      kibana_access: ro
      proxy_auth: ["VIET"]
      indices: [ "*vietnam*", ".kibana"]

    - name: "congo"
      type: allow
      kibana_access: ro
      proxy_auth: ["CONGO"]
      indices: [ "*congo*", ".kibana"]
```

Our current configuration derives from https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#local-users-and-groups.

We still cannot have a user with access to multiple acls/groups. 
Actually, defining a **congo** and a **vietnam** groups breaks the access for **CONGO** and **VIET** user:

```
    - name: "vietnam"
      type: allow
      kibana_access: ro
      groups: [ "vietnam" ]
      proxy_auth: ["VIET"]
      indices: [ "*vietnam*", ".kibana"]

    - name: "congo"
      type: allow
      kibana_access: ro
      groups: [ "congo" ]
      proxy_auth: ["CONGO"]
      indices: [ "*congo*", ".kibana"]

    - name: "congo_and_viet"
      type: allow
      kibana_access: ro
      proxy_auth: ["CG_VT"]
      indices: [ "*congo*", "*vietnam*", ".kibana"]

    users:

    - username: "MULTI_GROUP"
      proxy_auth: [ "MULTI_GROUP" ]
      groups: [ "congo", "vietnam" ]
```

**VIET** is denied access:
```
[2019-01-11T16:00:28,049][INFO ][t.b.r.a.ACL              ] [mCMhoMa] FORBIDDEN by default req={ ID:79431836-2016116393#2502, TYP:ClusterStateRequest, CGR:N/A, USR:[no basic auth header], BRS:true, KDX:null, ACT:cluster:monitor/state, OA:127.0.0.1, DA:127.0.0.1, IDX:, MET:GET, PTH:/_cat/indices?pretty, CNT:<N/A>, HDR:{User-Agent=curl/7.37.0, content-length=0, x-forwarded-user=VIET, Host=localhost:9203, Accept=*/*}, HIS:[::LOGSTASH::->[auth_key->false]], [::KIBANA-SRV::->[auth_key->false]], [::PHP::->[auth_key->false]], [::NAGIOS::->[auth_key->false]], [HQ Admins->[proxy_auth->false]], [vietnam->[proxy_auth->true, groups->false]], [congo->[proxy_auth->false]], [congo_and_viet->[proxy_auth->false]] } 
```
from the log above it seems because he does not match any group...

with the above configuration only **CG_VT** ( who has an acl for him only ) is allowed access: 

```
[2019-01-11T15:57:41,500][INFO ][t.b.r.a.ACL              ] [mCMhoMa] ALLOWED by { name: 'congo_and_viet', policy: ALLOW, rules: [kibana_access, proxy_auth, indices]} req={ ID:255744656-1789462282#2408, TYP:ClusterStateRequest, CGR:N/A, USR:CG_VT, BRS:true, KDX:null, ACT:cluster:monitor/state, OA:127.0.0.1, DA:127.0.0.1, IDX:all-vuln-ass-score-congo,all-sec-incidents-congo,all-vuln-ass-all-congo,all-sec-incidents-congo-alias,all-ib-blue-coat-sub-congo-alias,all-ib-blue-coat-sub-vietnam,all-vuln-ass-all-vietnam-alias,all-vuln-ass-all-congo-alias,all-sec-incidents-vietnam,all-vuln-ass-score-vietnam-alias,all-sec-incidents-vietnam-alias,all-vuln-ass-all-vietnam,.kibana,all-ib-blue-coat-sub-vietnam-alias,all-va-latest-all-vietnam,all-ib-blue-coat-sub-congo,all-va-latest-score-vietnam,all-va-latest-all-congo,all-va-latest-score-congo,all-vuln-ass-score-congo-alias,all-vuln-ass-score-vietnam, MET:GET, PTH:/_cat/indices?pretty, CNT:<N/A>, HDR:{User-Agent=curl/7.37.0, content-length=0, x-forwarded-user=CG_VT, Host=localhost:9203, Accept=*/*}, HIS:[::LOGSTASH::->[auth_key->false]], [::KIBANA-SRV::->[auth_key->false]], [::PHP::->[auth_key->false]], [::NAGIOS::->[auth_key->false]], [HQ Admins->[proxy_auth->false]], [vietnam->[proxy_auth->false]], [congo->[proxy_auth->false]], [congo_and_viet->[kibana_access->true, indices->true, proxy_auth->true]] } 
```

Moreover, if we strip off the proxy_auth rule from the ACLs and put them again in local users, still the **MULTI_GROUP** user has access only to the indexes of only one group (the first found in the yml file).

So, the question is if it's possible for a user to access the indexes of two different ACLs, and how.

**Comment by sscarduzio** [comment]
Yes it's possible using proxy_auth to have a user accessing both viet and congo (if you stop using local groups).

```yml
 - name: "vietnam"
      type: allow
      kibana_access: ro
      proxy_auth: ["VIET", "VIET_CONGO"]
      indices: [ "*vietnam*", ".kibana"]

    - name: "congo"
      type: allow
      kibana_access: ro
      proxy_auth: ["CONGO", "VIET_CONGO"]
      indices: [ "*congo*", ".kibana"]
```

Now the user "VIET_CONGO" can have a read-only Kibana session seeing both congo and vietnam indices.

The example you pointed out is different than what you are trying to do because in the example, the "username" value is the same string of user bit in the "auth_key".
