### ISSUE TITLE
Error trying to log in: groupCurrent not found (probably it's never been set)

### ISSUE THREAD

**Issue by Dave-c-Ross** [sscarduzio/elasticsearch-readonlyrest-plugin#428]
I've installed ES plugin and Kibana plugin and I get this error in kibana log: "groupCurrent not found (probably it's never been set)" when I try to log in. I've created a really simple config file to be able to log in. But still, I enter my credential, I see a short time error message saying something about a JSON token < not recognizes (so probably a HTLM return instead of a JSON), and then the login screen come back without any error message .. Anyone got this too ?

My config: (running both es and kib on 6.7.0)

```
readonlyrest:
    access_control_rules:

    - name: "Require HTTP Basic Auth"
      type: allow
      auth_key: user:password 
```

Any idea ?

**Comment by Dave-c-Ross** [comment]
And here's the visual error I got on kibana while trying to login:


Something went wrong
Try refreshing the page. If that doesn't work, go back to the previous page or clear your session data.


Clear your session

Go back
Unexpected token < in JSON at position 0
Version: 6.7.0
Build: 20221
SyntaxError: Unexpected token < in JSON at position 0
    at Object._callee$ (http://10.195.197.167:30015/built_assets/dlls/vendors.bundle.dll.js:229:104985)
    at tryCatch (http://10.195.197.167:30015/built_assets/dlls/vendors.bundle.dll.js:497:447406)
    at Generator.invoke [as _invoke] (http://10.195.197.167:30015/built_assets/dlls/vendors.bundle.dll.js:497:451288)
    at Generator.prototype.(anonymous function) [as next] (http://10.195.197.167:30015/built_assets/dlls/vendors.bundle.dll.js:497:448529)
    at asyncGeneratorStep (http://10.195.197.167:30015/built_assets/dlls/vendors.bundle.dll.js:229:99828)
    at _next (http://10.195.197.167:30015/built_assets/dlls/vendors.bundle.dll.js:229:100128)

**Comment by Dave-c-Ross** [comment]
and in elastic logs : [2019-04-11T15:47:08,257][INFO ][t.b.r.a.ACL              ] [es-data-ff755d769-cjvmr] FORBIDDEN by default req={ ID:2068135715-1006255268#677, TYP:MainRequest, CGR:N/A, USR:[no basic auth header], BRS:true, KDX:null, ACT:cluster:monitor/main, OA:10.195.197.197, DA:10.42.33.7, IDX:<N/A>, MET:GET, PTH:/, CNT:<N/A>, HDR:{User-Agent=Go-http-client/1.1, content-length=0, Host=10.195.197.197:30018, Accept-Encoding=gzip, Accept=application/json}, HIS:[Local user->[auth_key->false]], [::KIBANA-SRV-Local::->[auth_key->false]] }

**Comment by sscarduzio** [comment]
have you set up elasticsearch username and password in kibana.yml?

**Comment by Dave-c-Ross** [comment]
yes I did
```
elasticsearch.hosts: "http://es-client:9200"
elasticsearch.username: user
elasticsearch.password: password
```

**Comment by sscarduzio** [comment]
@Dave-c-Ross  is this ROR PRO? What version?

**Comment by sscarduzio** [comment]
USR:[no basic auth header], BRS:true, KDX:null, ACT:cluster:monitor/main, OA:10.195.197.197, DA:10.42.33.7, IDX:<N/A>, MET:GET, PTH:/, CNT:<N/A>, HDR:{User-Agent=Go-http-client/1.1, content-length=0, Host=10.195.197.197:30018, Accept-Encoding=gzip, Accept=application/json}, HIS:[Local user->[auth_key->false]], [::KIBANA-SRV-Local::->[auth_key->false]] }

I can see:

1. Your ACL is made of two blocks, not one like showed (see "HIS:" section)
2. The request that is being forbidden arrives from a go-http-client, not from Kibana
3. The request carries no basic auth credentials (see USR: section)

**Comment by Dave-c-Ross** [comment]
Probably my pod readyness probe picking on the kibana endpoint, I'm running enterprise on k8s.

I changed my config for:

```
readonlyrest:
    access_control_rules:
    - name: "Local user"
      type: allow
      auth_key: user:password 
    - name: "::KIBANA-SRV-Local::"
      type: allow
      auth_key: user:password
```

But still, when I try to login using kibana, I get the JSON token < error.

**Comment by sscarduzio** [comment]
The JSON token error is because kibana gets "forbidden" and returns the login page from an ajax call. You should find the correct "forbidden" log line and start from there.

Also, FYI the two ACL blocks are functionally identical, it's like having a single one. The second will never match.

**Comment by Dave-c-Ross** [comment]
I'm still looking at my ES log but found nothing related as up right now, but in the mean time I changed the config using your exemple here https://github.com/sscarduzio/readonlyrest-cluster-example.

```
readonlyrest:
    prompt_for_basic_auth: false

    access_control_rules:

    - name: "::LOGSTASH::"
      auth_key: logstash:logstash
      actions: ["indices:data/read/*","indices:data/write/*","indices:admin/template/*","indices:admin/create"]
      indices: ["logstash-*"]

    - name: "::KIBANA-SRV::"
      auth_key: kibana:kibana

    - name: "::RO::"
      auth_key: ro:dev
      kibana_access: ro
      indices: [ ".kibana", ".kibana-devnull", "logstash-*"]
      kibana_hide_apps: ["readonlyrest_kbn", "timelion", "kibana:dev_tools", "kibana:management"]

    - name: "::RW::"
      auth_key: rw:dev
      kibana_access: rw
      indices: [".kibana", ".kibana-devnull", "logstash-*"]
      kibana_hide_apps: ["readonlyrest_kbn", "timelion", "kibana:dev_tools", "kibana:management"]


    - name: "::ADMIN::"
      auth_key: admin:dev
      # KIBANA ADMIN ACCESS NEEDED TO EDIT SECURITY SETTINGS IN ROR KIBANA APP!
      kibana_access: admin

    - name: "::WEBSITE SEARCH BOX::"
      indices: ["public"]
      actions: ["indices:data/read/*"]
```

I changed my kibana settings as follow: 
```
server:
  name: "elastic-cluster"
  host: "0"
  port: "5601"
  defaultRoute: "/app/kibana"

elasticsearch.hosts: "http://es-client:9200"
elasticsearch.username: kibana
elasticsearch.password: kibana


logging.verbose: true

console.enabled: true

xpack.monitoring.enabled: false

xpack:
  security.enabled: false
```

And made sure that security was disabled in elasticsearch.yml too
```
cluster:
  name: ${CLUSTER_NAME}
node:
  master: ${NODE_MASTER}
  name: ${NODE_NAME}
  data: ${NODE_DATA}
  ingest: ${NODE_INGEST}
network:
  host: ${NETWORK_HOST:0.0.0.0}
bootstrap:
  memory_lock: ${MEMORY_LOCK:false}
discovery:
  zen:
    ping.unicast.hosts: ${DISCOVERY_SERVICE}
    minimum_master_nodes: ${NUMBER_OF_MASTERS}
xpack:
  security:
    enabled: false
```

I still have the same behavior, I'll try to catch the good log line
