### ISSUE TITLE
Some actions don't consider the configured index

### ISSUE THREAD

**Issue by lucasmogari** [sscarduzio/elasticsearch-readonlyrest-plugin#451]
I'm trying to configure the logic below, but it's now working. In the log line the IDX is <N/A> but the PTH is /kibana_sample_data_flights/_doc/Eddu62oBXvooVOsgWoRf?pretty. Is it a bug? Or how do I have to configure this kind of logic?

Logic:
Allow all write actions to "kibana_sample_*"
Deny all write actions to "kibana_sample_data_flight"

Using:
ES 7.0.2
ROR 1.18.0_es7.0.1

Config:
```
    - name: "user:forbidden"
      type: forbid
      actions:
        - "indices:data/write/*"
      indices:
        - "kibana_sample_data_flight"
      jwt_auth:
        name: jwt_provider_1
        roles: ["users"]
    - name: "user"
      actions:
        - "indices:data/write/*"
      indices:
        - "kibana_sample_*"
      jwt_auth:
        name: jwt_provider_1
        roles: ["users"]
```

Log:
```
[2019-05-24T17:10:53,458][INFO ][t.b.r.a.l.AclLoggingDecorator] [tetris.local] ALLOWED by { name: 'user', policy: ALLOW, rules: [jwt_auth,indices,actions] req={  ID:448605991-1536035407#121,  TYP:DeleteRequest,  CGR:N/A,  USR:user,  BRS:false,  KDX:null,  ACT:indices:data/write/delete,  OA:127.0.0.1/32,  XFF:x-forwarded-for=127.0.0.1,  DA:127.0.0.1/32,  IDX:<N/A>,  MET:DELETE,  PTH:/kibana_sample_data_flights/_doc/Eddu62oBXvooVOsgWoRf?pretty,  CNT:<N/A>,  HDR:Host=dev.localhost:9200, authorization=<OMITTED>,  HIS:[Kibana-> RULES:[auth_key->false], RESOLVED:[]], [SuperAdmin-> RULES:[jwt_auth->false], RESOLVED:[]], [user:forbidden-> RULES:[jwt_auth->true, indices->false], RESOLVED:[user=user;group=users;av_groups=users]], [user-> RULES:[jwt_auth->true, indices->true, actions->true], RESOLVED:[user=user;group=users;av_groups=users]]  }
```
