### ISSUE TITLE
Checking index config failed: Cannot find index with ROR configuration

### ISSUE THREAD

**Issue by bseehra** [sscarduzio/elasticsearch-readonlyrest-plugin#458]
After upgraded to ES 7.2.0 with ROR 1.18.2-pre2_es7.2.0 plugin installed, the ES logs are filling up with the following entry:

```
[2019-07-03T19:22:57,686][WARN ][t.b.r.b.RorInstance      ] [72217a4a67ad] [CLUSTERWIDE SETTINGS] Checking index config failed: Cannot find index with ROR configuration
```

What is the correct setting / location to force ROR to use the config file vs. in-index settings?

When I tried to add force_load_from_file to elasticsearch.yml, I'm getting this error on startup:

```
[2019-07-03T19:29:13,243][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [72217a4a67ad] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [readonlyrest.force_load_from_file] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
```

**elasticsearch.yml**

```
http:
  port: 9200
path:
  data: /elasticsearch/data
transport:
  tcp:
    port: 9300
network:
  host: 172.17.0.3
  publish_host: 172.17.0.3
  bind_host: 0.0.0.0
cluster:
  name: elasticsearch-cluster
node:
  name: 72217a4a67ad
  master: true
  data: true
  ingest: false
discovery:
  type: single-node
readonlyrest:
  force_load_from_file: true
```
