### ISSUE TITLE
Include actions references in Wiki

### ISSUE THREAD

**Issue by elpaquete** [sscarduzio/elasticsearch-readonlyrest-plugin#46]
I've been trying to understand the possible values for the actions field in the [Supported Rules](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/wiki/Supported-Rules) page and by reviewing the code, both of the plugin and ES.

Is this value specific to the data, as the indices are? Or does it refer to the diferent APIs and actions in the [elastic search docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html)?If it's the latter, it would be great to have a list or something. 

In the code I see that it picks it up from the ActionRequest in the RequestContext, but I'm unable to follow what kind of actions are defined in ES.

I'm a bit new around ES, so this might be something I'm missing as a rookie.

Thanks.

**Comment by sscarduzio** [comment]
You're totally right, myself I had the same question. The actions are defined somewhere in ES code, and what they mean is not well documented.  But they can be audited using logs when you use a particular app. 

You should see the toString of RequestContext being logged when ES is in debug mode if I recall correctly..

You can see an example of what actions I needed to let through to support Kibana (ref. KibanaAccessRule class) that list comes from the official docs on how to configure Shield for Kibana.

It's not much info, but I hope it helps. Probably if you share more on what is your objective I could be more helpful:)

**Comment by elpaquete** [comment]
Thanks for the prompt response. I will start to look into the logs.

I want to provide a set of API keys to:
- A master key with allow all.
- A write key that will allow CRUD operations on documents.
- A read key.

From what I see in the docs, this could be something like 

```yaml
readonlyrest:
    enable: true
    response_if_req_forbidden: Forbidden!
    access_control_rules:
    - name: Master
      type: allow
      api_keys: [masterkey]

    - name: Write
      type: allow
      api_keys: [writekey]
      actions: [indices:data/*]

    - name: Read
      type: allow
      api_keys: [readkey]
      actions: [indices:data/read/*]
```

However, I don't know (yet) if will enable search for the requests with the Read key.
