### ISSUE TITLE
Tests ES level rules in a cluster

### ISSUE THREAD

**Issue by sscarduzio** [sscarduzio/elasticsearch-readonlyrest-plugin#52]
Repeat tests mentioned in #50 within a cluster and try to reproduce the weird behavior seen in #50 in a multi node environment.

In general, would be good to add test coverage for clustered ES with sharded indices.

**Comment by reqless** [comment]
Any updates with this?

**Comment by sscarduzio** [comment]
Nope, I've been really busy this week, hopefully next weekend I can set something up (docker compose?) to automate cluster testing.

**Comment by michaelseto** [comment]
Great!

**Comment by nitram4** [comment]
Im using readonly plugin for accessing Elasticsearch cluster through Kibana server but just on only one node (which is the only one open to inside network, other are closed by iptables). Recently i have received "authentication exception" on that node before #50 was open. I could not fix it event after plugin disabled. Only vanilla reinstall of Elasticsearch client helped. Since then I could not reproduce the issue.

**Comment by reqless** [comment]
Any progress on this?

**Comment by nitram4** [comment]
Hello, 
i have reproduced #50  issue when installing Kibi on the node. Kibi is fork of Kibana, enahancing with some features. Currently I have as well Kibana 4.5 and working with no problems, but Kibi 4.4.2 is experiencing "Authentication exception"

Here is my config in ES:

readonlyrest:
    enable: true
    response_if_req_forbidden: Forbidden
    access_control_rules:
    - name: Kibana Server
      type: allow
      kibana_access: rw
      auth_key: kibana_server:xxxxx
    - name: Kibi Server
      type: allow
      kibana_access: rw
      kibana_index: .kibi
      auth_key: kibi_server:xxxxxxx


Here is DEBUG log from data node, only this one:

`[2016-06-19 00:19:04,239][DEBUG][index.search.slowlog.query] [.kibi]took[303.2micros], took_millis[0], types[config], stats[], search_type[QUERY_AND_FETCH], total_shards[1], source[{"size":1000,"sort":[{"buildNum":{"order":"desc","ignore_unmapped":true}}]}], extra_source[],
`

Kibi log:
`  log   [00:19:13.733] [warning][query_engine] Could not retrieve Kibi index: Error: Authentication Exception
  `
Im troubleshooting it 2 hours and could not find the issue. But at least I can reporoduce it.
Any thougts?

**Comment by sscarduzio** [comment]
Hey @nitram4, thanks for coming back with useful data on this awful one. A few questions for you:
1. does it work as expected if you use rw+?
2. no debug/trace lines saying what was the action being rejected?
3. could you show your yml with the actual indentation? I.e. use the github markdown backticks to show it as code.
4. is this reproducible in a single node?

**Comment by nitram4** [comment]
I will try it tomorrow on my testing node. Could you please advise how to enable debug mode of the cluster itself, because I have managed to enable slowlog for certain index (dont want to play on the production cluster and enable for all indices). I could not get to ACTION log that you have mentioned on the web. The only i had was the log above.

Thanks

**Comment by sscarduzio** [comment]
Unfortunately at the moment you'd need to enable debug logging globally on es. I need to make it configurable for the plugin alone, you're right!

**Comment by ld57** [comment]
Hi,

Currently implementing on a cluster of 3 nodes with logstash 2.3.4, kibana 4.5.2, elasticsearch 2.3.4 and grafana 3.02.
I will say if I meet some issue.

here my 5cts regarding logging method for the plugin : 
I managed to redirect all logs regarding the plugin readonlyrest to a dedicated file, in DEBUG mode, while letting es global log method as INFO.

here my logging.yml modification

> Just complete logging.yml section by adding dedicated lines for readonlyrest

```
logger:
 #Plugin readonly rest logging to dedicated file
  plugin.readonlyrest.acl.blocks.rules.impl: DEBUG, access_log_file
  plugin.readonlyrest.acl: DEBUG, access_log_file
```
```
additivity:
 #Plugin readonly rest exclusion from ES main log file
  plugin.readonlyrest.acl.blocks.rules.impl: false
  plugin.readonlyrest.acl: false
```

```
appender:
 #Plugin readonly rest logging file definition
  access_log_file:
    type: dailyRollingFile
    file: ${path.logs}/${cluster.name}_access.log
    datePattern: "'.'yyyy-MM-dd"
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
```
