### ISSUE TITLE
Support only allow create and read?

### ISSUE THREAD

**Issue by sinkcoder** [sscarduzio/elasticsearch-readonlyrest-plugin#526]
Hello,
I want  to set my elasticsearch only accept create and read requests, is this plugin support this mode?
Thanks.
: )

**Comment by sscarduzio** [comment]
Hello @sinkcoder, of course.

Do you mean at the Elasticsearch API level? Like, you have some log shipping agents? 

If this is about pure Elasticsearch API consumers, I recommend using the actions rule, i.e.

```
readonlyrest:
   enable: true
   access_control_rules:
    - name: "Allow read and create"
       auth_key: "agent1user:passwd"
       actions: ["indices:*/create*", "indices:*/get", "indices:*write/index", "indices:*get","indices:*search"]

```

The above is just a top of the head example, I suggest taking this into use, and add any extra actions you need to allow by testing your API consumer and seeing if the plugin blocks any more action.

The list of available actions [can be found here](https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#actions).

In the case this is a Kibana user you want to give read and create privileges, you can have as a starting point the macro rule: "kibana_access: ro". Find [description and example here](https://github.com/beshu-tech/readonlyrest-docs/blob/master/elasticsearch.md#kibana_access)

**Comment by sinkcoder** [comment]
@sscarduzio Thank you for your recommendations!
I use the actions above and add extra actions to block update requests like `PUT /<index>/_doc/<_id>`
```
readonlyrest:
  enable: true
  access_control_rules:
  - name: "Forbid update"
    type: forbid 
    methods: [POST, PUT]
    uri_re: ["^/.*/.*/.+"]

  - name: "Allow read and create"
    actions: ["indices:*/create*", "indices:*/get", "indices:*write/index", "indices:*get", "indices:*search"]
```
It seems to work well.Thank you!
