### ISSUE TITLE
LDAP Anonymous Bind not working

### ISSUE THREAD

**Issue by alvinlee001** [sscarduzio/elasticsearch-readonlyrest-plugin#547]
I have successfully integrated the ROR plugin with LDAP, below is the settings, but after removing the `bind_dn` and `bind_password`, I cannot log in anymore 

```
readonlyrest:

  response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin
  access_control_rules:

  # - name: "Require HTTP Basic Auth"
  #   type: allow
  #   auth_key: user:password 

  - name: "IT"
    # kibana_access: admin
    ldap_auth:
      name: "ldap1"
      groups: ["IT"]
    type: allow 

  ldaps:
  - name: ldap1
    host: "192.168.0.1"
    port: 389
    # bind_dn: "CN=user,OU=Users,OU=Malaysia,DC=MY,DC=example,DC=local"
    # bind_password: "password"
    ssl_enabled: false
    ssl_trust_all_certs: true
    search_user_base_DN: "OU=Users,OU=Malaysia,DC=MY,DC=example,DC=local"
    search_groups_base_DN: "OU=Malaysia,DC=MY,DC=example,DC=local"
    user_id_attribute: "samAccountName"
    unique_member_attribute: "member"
    connection_pool_size: 10
    connection_timeout_in_sec: 30
    request_timeout_in_sec: 30
    cache_ttl_in_sec: 60
    group_search_filter: "(objectclass=group)"

``` 

Is there anything else to configure for LDAP anonymous authentication? From the examples, it says "skip for anonymous bind" for the `bind_*` fields.
