### ISSUE TITLE
ACL based on host.

### ISSUE THREAD

**Issue by hecrogu** [sscarduzio/elasticsearch-readonlyrest-plugin#68]
Hi!,

I was using your plugin in an older version of elasticsearch (2.1.2). Now I upgrade my elastic's version to 2.3.2 and update your plugin version to 1.9.3, which should be compatible with elastic 2.3.2, but my old configuration of your plugin doesn't works. Is it any change in the way of applied that configuration?

My old configuration was in elasticsearch.yml and contains: 
``

```
# Readonlyrest plugin
readonlyrest:
    # (De)activate plugin
    enable: true

    # HTTP response body in case of forbidden request.
    # If this is null or omitted, the name of the first violated access control rule is returned (useful for debuggi$
    response_if_req_forbidden: Sorry, your request is forbidden

    # Default policy is to forbid everything, let's define a whitelist
    access_control_rules:

    # from these IP addresses, accept any method, any URI, any HTTP body
    - name: full access to internal servers
      type: allow
      hosts: [127.0.0.1, ip1, ip2]

```

``
But for now i can access from every site.

Thanks for your work.
