### ISSUE TITLE
actions not working as list

### ISSUE THREAD

**Issue by abbasovalex** [sscarduzio/elasticsearch-readonlyrest-plugin#74]
First of all, great thank for your plugin! You are rock! But I need help with some settings. I mean about actions. I can't setup multiple rules for actions. If I set like documentation elastic would not start with it.

My enviroment:
CentOS Linux release 7.2.1511 (Core)

Elasticsearch
`{
  "name" : "name-spb1",
  "cluster_name" : "cluster-prod",
  "version" : {
    "number" : "2.2.0",
    "build_hash" : "8ff36d139e16f8720f2947ef62c8167a888992fe",
    "build_timestamp" : "2016-01-27T13:32:39Z",
    "build_snapshot" : false,
    "lucene_version" : "5.4.1"
  },
  "tagline" : "You Know, for Search"
}
`

elasticsearch.yml (not working)
```
readonlyrest:
    enable: true
    response_if_req_forbidden: Forbidden
    access_control_rules:

    - name: Backup
      type: allow
      hosts: 127.0.0.1
      actions: [cluster:*, indices:*]
      auth_key: admin:1234
```

If I set actions as examle as  without bracket and single it would be ok:
Into elasticsearch.yml set

```
readonlyrest:
    enable: true
    response_if_req_forbidden: Forbidden
    access_control_rules:

    - name: Backup
      type: allow
      hosts: 127.0.0.1
      actions: cluster:*  # or actions: indices:*
      auth_key: admin:1234
```

I have small request to you. Please to add example to actions for **_snapshot** API

Great thank you, guys! Rock!
