### ISSUE TITLE
<no-index> seems not work on readonlyrest-v1.7

### ISSUE THREAD

**Issue by tottishi05** [sscarduzio/elasticsearch-readonlyrest-plugin#78]
ElasticSearch version: 1.7.4
readonlyrest version: 1.7

part of elasticsearch.yml

```
readonlyrest:
    enable: true
    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin
    access_control_rules:

    - name: "test"
      type: allow
      actions: ["cluster:*", "indices:data/read/*"]
      indices: ["<no-index>", "test"]
```

When I type "http://192.168.118.128:9200/_cluster/health" in my browser, it returns in the log: 
**[WARN ][plugin.readonlyrest.acl.blocks.rules.impl] didn't find any index for this request: GET /_cluster/health**
