### ISSUE TITLE
elasticsearch 1.6.0 operations

### ISSUE THREAD

**Issue by maq123** [sscarduzio/elasticsearch-readonlyrest-plugin#8]
I have built readonlyrest-plugin for ES 1.6.0 according to readme instructions and installed it correctly.
However it seems ACL rules are not interpreted correctly.

My config : 
```
readonlyrest:
     # (De)activate plugin
     enable: true

     # HTTP response body in case of forbidden request.
     # If this is null or omitted, the name of the first violated access control rule is returned (useful for debugging!)
     response_if_req_forbidden: Sorry, your request is forbidden

     # Default policy is to forbid everything, let's define a whitelist
     access_control_rules:

     - name: restricted access to all other hosts
     type: allow
     methods: [OPTIONS,GET]
     maxBodyLength: 0
```

While testing I got : 

```
root@kibana:/tmp/elasticsearch-readonlyrest-plugin# curl 'localhost:9200/_cat/nodes?v' -v -XGET
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 9200 (#0)
> GET /_cat/nodes?v HTTP/1.1
> User-Agent: curl/7.38.0
> Host: localhost:9200
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json; charset=UTF-8
< Content-Length: 51
<
* Connection #0 to host localhost left intact
{"error":"NullPointerException[null]","status":500}
```

**Comment by sscarduzio** [comment]
Good catch, I'll have a look tomorrow morning.

**Comment by sscarduzio** [comment]
You have an error in the configuration file: please indent the lines is after "- name ...".  So instead of:
```yaml
     ...
     - name: restricted access to all other hosts
     type: allow
     methods: [OPTIONS,GET]
     maxBodyLength: 0
```
You should have something like: 
```yaml
     ...
     - name: restricted access to all other hosts
       type: allow
       methods: [OPTIONS,GET]
       maxBodyLength: 0
```

True that I can improve the plugin so it will throw an exception about bad configuration instead of failing at runtime. Will do.
