### ISSUE TITLE
issue with the "indices:" rule.

### ISSUE THREAD

**Issue by met3or** [sscarduzio/elasticsearch-readonlyrest-plugin#86]
Hi!  I have been trying to use your module this afternoon for the purpose of creating specific users to have read only access over Kibana to browse a particular wildcard group of indices.

Unfortunately I've been running into the following error:

`[2016-07-29 16:55:21,984][INFO ][plugin.readonlyrest.acl  ] no block has matched, forbidding by default: { action: indices:data/read/mget, OA:192.x.0.x, indices:[.kibana], M:POST, P:/_mget, C:{"docs":[{"_index":".kibana","_type":"config","_id":"4.4.2"}]}, Headers:[]}`

When trying to login as the defined ro user in Kibana.  This problem only presents itself when applying the "indices:" configuration.  When removing this, we can login but do not have the necessary index restrictions.

We're using the below config:

```
http.cors.enabled: true
http.cors.allow-origin: /http?:\/\/host\.name\.here\.co\.uk(:[0-9]+)?/

readonlyrest:
    enable: true
    response_if_req_forbidden: Forbidden by ReadonlyREST ES plugin
    access_control_rules:

    - name: Kibana Server (we trust this server side component, full access granted via HTTP authentication)
      auth_key: admin:passwd3
      type: allow

    - name: user
      auth_key: user:pass
      type: allow
      kibana_access: ro
      kibana_index: .kibana
      indices: ["<no-index>", "index-name-01*"]
```

I've tried altering the values in the indices array with an assortment of different things, such as exact index names, and different wildcard searches.  

Any help would be really appreciated,

Regards,
