### ISSUE TITLE
Kibana ::1:<port> ECONNREFUSED

### ISSUE THREAD

**Issue by mrlexor** [sscarduzio/elasticsearch-readonlyrest-plugin#957]
Hello,

I've deployed ECK alongside with Readonlyrest according to [instruction](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/tree/develop/eck) where one Kibana and three Elastic instances were deployed. Everything is started up fine, but Kibana showed `Internal server error` after trying to log into WEB UI. 

I noticed the following following message in the logs of Kibana service:
```
[info][plugins][ReadonlyREST][preElasticsearchProxy] Pre-Elasticsearch-proxy will listen on 127.0.0.1:59831
...
[elasticsearch-service] ::1: 59831 ECONNREFUSED
```

After some research I found out that Readonlyrest starts `Pre-Elasticsearch-proxy` on random port and then changes `kibana.yaml` where replacing `elasticsearch.host` to `[http://localhost:59831]` and this action cause the error above because DNS resolver starts to resolve `localhost` to `::1` instead of `127.0.0.1` where `Pre-Elasticsearch-proxy` is listening the port `59831`. This behaviour is due to when kibana service is starting it is changing `/etc/hosts` and adding the following line there:
```
::1 localhost ip6-localhost ip6-loopback
```

In order to fix this issue I updated the script `/usr/share/kibana/plugins/readonlyrestkbn/kibana/config/kibanaYamlKibanaConfigParser.js` using the following command in `Dockerfile` of kibana service:
```
RUN sed -ie 's/localhost/127.0.0.1/g' /usr/share/kibana/plugins/readonlyrestkbn/kibana/config/kibanaYamlKibanaConfigParser.js
```

So it seems like that would be better to run `Pre-Elasticsearch-proxy` on `127.0.0.1` and then modify configs of all related services with specifying `127.0.0.1` IP address instead of `localhost`.

**ror_kbn_universal:** 1.52.0
**ror_es:** 1.52.0
**eck-operator:** 2.10.0
**eck-stack:** 0.8.0
- Elastic: 8.10.4
- Kibana: 8.10.4

**Comment by coutoPL** [comment]
Thanks for reporting this. We are aware and the fix will be included in the upcoming release ROR 1.53.0.

**Comment by coutoPL** [comment]
The fix is released together with other changes in ROR 1.53.0.
@mrlexor do you confirm it works now?

**Comment by mrlexor** [comment]
Hello,

Thank you for the fix, but unfortunately I can’t check it, because I decided to stop using Readonlyrest plugin for now.

**Comment by sscarduzio** [comment]
So sad he ditched the whole ROR for this bug. I understand him though, the man had a task and this was a blocker. 

@mrlexor you are welcome to try ReadonlyREST anytime. If you do, we will upgrade you to priority support, the same we deliver to Enterprise user. 🫶

**Comment by mrlexor** [comment]
@sscarduzio thank you for the opportunity, but that bug wasn’t a reason why I decided to stop using RoR. Actually, the main reasons are in other two things which I met during review the plugin:
1. Sometimes it couldn’t connect to LDAP server (I found out the similar issue in GitHub and there it was fixed, but I met it anyway)
2. Unexpected logout in case to opening restricted section of stack management, for example.

I just don’t have enough time for researching it and I keep using ECK without plugins.

**Comment by sscarduzio** [comment]
@mrlexor this is enormously useful feedback for us. Thanks for taking the time to report back on it.

1. Are you able to find the similar issue? Might be a regression worth checking for us.

2. You are absolutely right. This has to change. And primarily we need to hide from the GUI what users have no permissions to click on.

**Comment by mrlexor** [comment]
@sscarduzio Yes, I can, here it is - https://forum.readonlyrest.com/t/losing-connections-to-ldap-servers/1485

It looks like the exactly what I met, unexpected connection timeouts meanwhile other applications connected to LDAP server are working fine.

**Comment by sscarduzio** [comment]
@coutoPL the issue @mrlexor pointed out is old, yet, two years later someone else added a message to the thread lamenting the same issue as well (no answer provided 😳)

**Comment by coutoPL** [comment]
According to the forum's topic - some time ago there was a problem with the proper handling of of timeouts in the LDAP client we use. The issue was fixed. @mrlexor it'd be great if you could show us your log with the exception. Because the problem described in the last post on the forum would be worth checking if you also experienced it. 

But ... in general when clients see `timeout [85]` it's a common problem, that in most cases is a problem with the LDAP server (too many requests to handle, so it's starting to struggle) or bad configuration of the LDAP connector in the ROR settings. Did you use ROR's LDAP caching? What were your LDAP connector settings? 

>  in 30 minutes and then periodically it is appearing and affecting log in for users.

I guess that user were being logged out. Were they able to log in again?

**Comment by sscarduzio** [comment]
@mrlexor would be interesting to see if you have any LDAP parameter configurations (connection timeout, cache settings, etc) in your current working solution, so we can compare with our current defaults.

**Comment by mrlexor** [comment]
Sorry guys, but as I mentioned before I decided to stop using RoR, so I don't have an installation of this plugin at the moment.

@coutoPL I have the configuration which I applied while I was using RoR and here it is:
```YAML
readonlyrest:
  access_control_rules:
    - name: "Name of a group in AD"
      verbosity: error
      type: allow
      ldap_authentication: "ad"
      ldap_authorization:
        name: "ad"
        groups: ["Name of a group in AD"]
        kibana:
          access: unrestricted
  ldaps:
    - name: ad
      host: "ldaps.example.com"
      port: 636
      ssl_enabled: true
      ssl_trust_all_certs: true
      bind_dn: "CN=read-only,DC=example,DC=com"
      bind_password: "${env:LDAP_BIND_PASSWORD}"
      search_user_base_DN: "DC=users,DC=example,DC=com"
      user_id_attribute: "mail"
      unique_member_attribute: "member"
      search_groups_base_DN: "DC=groups,DC= example,DC=com"
      connection_pool_size: 10
      connection_timeout_in_sec: 30
      request_timeout_in_sec: 30
      cache_ttl_in_sec: 60
```

>  I guess that user were being logged out. Were they able to log in again?
It worked in that way for existing and new users. I mean when new users tried to log in they have the error `Wrong credentials` as well as existing users after logout couldn't login again.

@sscarduzio here the config above which I tried to use.
