### ISSUE TITLE
cluster actions not read-only

### ISSUE THREAD

**Issue by retzkek** [sscarduzio/elasticsearch-readonlyrest-plugin#97]
This might just be a documentation issue - the README gives the following example:

``` yaml
    - name: Just certain indices, and read only
      type: allow
      actions: ["cluster:*", "indices:data/read/*"]
      indices: ["<no-index>", "product_catalogue-*"] # index aliases are taken in account!
```

However, by allowing `cluster:*` actions, _anyone_ can perform cluster-level operations, like `PUT /cluster/_settings` (tested on elasticsearch 2.3.5 with readonlyrest 1.9.4). So giving it as a read-only example is quite misleading.

Is there a definitive read-only ruleset that works for client libs and tools like Grafana? This is what I've come up with, but there may be some giant hole hiding in one of those actions.

``` yaml
    - name: read-only
      type: allow
      # POST is used by some clients to do searches
      methods: [GET, OPTIONS, HEAD, POST]
      # admin/get is needed for mapping (to get field list)
      actions: ["indices:data/read/*","indices:monitor/*","indices:admin/get"]
      indices: ["*"]
```
